### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by OverlyExcessive** [haf/expecto#1]
referencing https://github.com/mausch/Fuchu/pull/51

There is still some work ahead, mainly with `Expecto.Tests`. NUnit has .NET Core as a platform target now. FsCheck seems to be pending support (https://github.com/fscheck/FsCheck/pull/293).

PerfUtil and MbUnit seem to be the main issues right now as none of them seem to be actively maintained anymore. @mausch mentioned possibly dropping support for MbUnit. The way I see it, the alternatives are either porting those libs to .NET Core and hoping that a PR can be accepted, forking them or dropping support for PerfUtil and MbUnit.

**Comment by haf** [comment]
I've dropped support for the other test frameworks in this test framework. I want a framework that's good for F#.

**Comment by MichaelBaker** [comment]
It sounds like this should work with Core, but when I add a dependency on `"Expecto": "1.0.12"
` to my project, I get these errors:

```
    Package Expecto 1.0.12 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). 
    Package FSharp.Core 3.1.2.5 is not compatible with netcoreapp1.0 Version=v1.0). Package 
```

Then when I add `"imports": ["net40" ]` to my project, it fails to compile with a lot of errors like: `The type referenced through 'System.String' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib'.`

So then I add `"Microsoft.NETCore.Portable.Compatibility": "1.0.1"` as a dependency and I get: `The module/namespace 'System.Net' from compilation unit 'System' did not contain the namespace, module or type 'WebClient'`

And now I'm stuck. What do I need to do to get this working on a core project? I'm happy to submit a PR with the necessary changes, but I'm not sure where to start.

**Comment by OverlyExcessive** [comment]
@MichaelBaker AFAIK there are a few things that need to be ported for Expecto to be fully .NET Core compatible.

For example FsCheck is still awaiting .NET Core support, pending https://github.com/fscheck/FsCheck/pull/293. 

Also like I mentioned earlier PerfUtil is dead and does not have .NET Core support, although @haf mentioned that support for PerfUtil could be dropped. Anyhow, the core project has been ported, what remains more or less is `Expecto.Tests` and `Expecto.FsCheck`. 

Unfortunately IRL work is taking up most of my time right now but feel free to ask if you need any further pointers.

**Comment by haf** [comment]
What should be used instead of PerfUtil?

**Comment by haf** [comment]
I switched the code over to using BenchmarkDotNet instead of PerfUtil.

Released v1.1 with this.

**Comment by haf** [comment]
Bookkeeping: https://github.com/haf/expecto/pull/4 fixed this issue, but the build is blocked on https://github.com/Albacore/albacore/issues/221.

**Comment by forki** [comment]
what is the status with .NET core support?

**Comment by haf** [comment]
See the comment just above yours.

**Comment by adamchester** [comment]
> what is the status with .NET core support?

>  See the comment just above yours.

That may have been true, but I don't think it is anymore. See #101 for example.

**Comment by haf** [comment]
Well, fscheck has moved forward, so it's only the actual work on #101 and albacore/#221 to be done :) 👍 Thanks for looking into it.

**Comment by wallymathieu** [comment]
An alternative approach in order to run the tests in .net 4.5 context (or 451 et.c.):

For instance having your code have the following frameworks:

```
  "frameworks": {
    "netstandard1.6": {
      "imports": [ "dnxcore50" ],
      "dependencies": {
        "YYY": "4.3.0"
      }

    },
    "net45": {
      "frameworkAssemblies": {
        "YYY": "4.0.0"
      }
    }
  }
```

Then the test assembly can be use ```net45```.

**Comment by haf** [comment]
If you're interested in Expecto for .Net core, please look at #101 now and review it.

**Comment by jmmk** [comment]
Is anything still blocking this? Is https://github.com/Albacore/albacore/issues/221 required to get a .net core build?

**Comment by adamchester** [comment]
Hi @jmmk, there is nothing really blocking this, except for someone finding the time. AFAIK, we just need to merge nupkg (from `dotnet`, with netstandard1.6 DLL) into the main albacore/nuget generated nupkg.

See the netcore branch.
