### ISSUE TITLE
Test the FTestAttribute behavior

### ISSUE THREAD

**Issue by MecuSorin** [haf/expecto#10]
We should test the FTestAttribute behavior:
- discovery(by reflection) of tests marked with this attribute
- propagation of the FocusedState to the child tests
- Expecto skipping other tests that are Normal

Note: This flag tests can influence the behavior of other tests based on reflection discovery.

**Comment by haf** [comment]
Is this an improvement request?

**Comment by MecuSorin** [comment]
It's a gap in the tests - just a sanity check. Didn't know how to create a meaningful automated test without creating a new project. By symmetry with PTestAttribute should work  - from discovery point of view - if all pending tests are working; propagation is tested.

**Comment by haf** [comment]
Would you like to PR this test? :)

**Comment by MecuSorin** [comment]
If you're OK with me creating a new test project just for this test, the I will do it. Do you have any preferences for folder structure/name ?

**Comment by haf** [comment]
Yes, please add a `testdata` folder to place it in to separate it out from the main projects.
