### ISSUE TITLE
Naming of nuget packages 

### ISSUE THREAD

**Issue by fbehrens** [haf/expecto#102]
Hi,

just get confused about results of searching  `Expecto` on  nuget:
https://www.nuget.org/packages?q=expecto i got following results.

I am getting multiple packages `Expecto Expecto`
```
 Expecto icon
Expecto Expecto By: henrik feldt
Last Published: 2017-02-18 | Latest Version: 4.0.1
Expecto is a smooth test framework for F#, cloned from Fuchu with added functionality for making it easier to use.
6,804 total downloads Tags testing fsharp assert expect

 Expecto.FsCheck icon
Expecto Expecto By: henrik feldt
Last Published: 2017-02-18 | Latest Version: 4.0.1
Expecto is a smooth test framework for F#, cloned from Fuchu with added functionality for making it easier to use.
5,105 total downloads Tags testing fsharp assert expect

 Expecto.BenchmarkDotNet icon
Expecto Expecto By: henrik feldt
Last Published: 2017-02-18 | Latest Version: 4.0.1
Expecto is a smooth test framework for F#, cloned from Fuchu with added functionality for making it easier to use.
2,075 total downloads Tags testing fsharp assert expect

 Expecto.PerfUtil icon
Expecto Expecto By: henrik feldt
Last Published: 2016-10-28 | Latest Version: 1.0.12
Expecto is a smooth test framework for F#, cloned from Fuchu with added functionality for making it easier to use.
1,124 total downloads Tags testing fsharp assert expect
```

When i look at https://www.nuget.org/packages/Expecto.BenchmarkDotNet/
it looks to me that that this is a separate module for benchmarking,
```
Expecto Expecto 4.0.1
Install-Package Expecto.BenchmarkDotNet
```

Seem like there is a display name in nuget is `Expecto Expecto` for the package `Expecto.BenchmarkDotNet`.

I can live with it, but maybe you like to look into this, and clean it up.
Cheers 😸

**Comment by haf** [comment]
Yes I know. It's because NuGet.org doesn't let me push them when they are named correctly. It gives 400 Bad Request with response that the package is named too similar to another package.

It's really frustrating and I don't know how to solve it :-(

**Comment by haf** [comment]
I've contacted the NuGet support, awaiting a reply.
