### ISSUE TITLE
Order of parameters in Expecto module

### ISSUE THREAD

**Issue by smoothdeveloper** [haf/expecto#107]
I was looking at samples https://github.com/haf/expecto/blob/master/Expecto.Sample/Expecto.Sample.fs and was wondering if there was value of making the API friendlier to piping or if the choice of order was made to discourage piping.

A simple example

```fsharp
Expect.isTrue subject "I compute, therefore I am."
```

It would make sense in certain cases to be able to write it that way instead:

```fsharp
subject |> Expect.isTrue "I compute, therefore I am."
```

That is passing the actual as last parameter.

That would be for sure a breaking change to the API, but maybe worth consideration if people using the library are looking forward more piping to the assertion functions.

**Comment by haf** [comment]
@smoothdeveloper How about a PR with the alternative ordering in a separate module? That way people can choose what they prefer.
