### ISSUE TITLE
Attributes in Readme

### ISSUE THREAD

**Issue by forki** [haf/expecto#109]
The readme shows basically only samples with attributes on tests. I personally prefer to have no attributes in my test code, but I know this might vary. Anyways I think at least the very first samples should work without attributes so that we show that there is no magic involved. @haf what do you think?

**Comment by haf** [comment]
Sure, we can add samples without attributes. Do you PR?

**Comment by haf** [comment]
Sure, we can add samples without attributes. Do you PR?

**Comment by forki** [comment]
will do.
