### ISSUE TITLE
Make test CE async

### ISSUE THREAD

**Issue by AnthonyLloyd** [haf/expecto#114]
I think this is just a drop in replacement and is fully backwardly compatible since bind was never implemented.

```
type TestCaseBuilder(name, focusState) =
    member b.Zero() = async.Zero()
    member b.Delay(f) = async.Delay(f)
    member b.Return(x) = async.Return(x)
    member b.ReturnFrom(x) = async.ReturnFrom(x)
    member b.Bind(p1, p2) = async.Bind(p1, p2)
    member b.Using(g, p) = async.Using(g, p)
    member b.While(gd, prog) = async.While(gd, prog)
    member b.For(e, prog) = async.For(e, prog)
    member b.Combine(p1, p2) = async.Combine(p1, p2)
    member b.TryFinally(p, cf) = async.TryFinally(p, cf)
    member b.TryWith(p, cf) = async.TryWith(p, cf)
    member __.Run f =
        match focusState with
        | Normal -> testCaseAsync name f
        | Focused -> ftestCaseAsync name f
        | Pending -> ptestCaseAsync name f


```

Will mean more test default to async which is a tiny bit less overhead.

test "my test" {

}

could then just be the recommended test signature and using let! is handy if you want to async at any point.

Since this become a `Test` I can't see any issues with it.

@haf what do you think?

Happy to put a PR in as I think its so simple. Happy to do the docs too but its up to you if we do it.

**Comment by haf** [comment]
I'd prefer not to throw away stack trace info and spring Asunción on unsuspecting programmers by default. Can't testAsync work?

**Comment by AnthonyLloyd** [comment]
Yes testAsync is an option. I'll put in a PR later.

Do you want to do anything to the docs to focus on test & testAsync rather than testCase?

**Comment by haf** [comment]
@AnthonyLloyd I leave that up to you. I'm pretty happy with the docs myself, but I believe you've been talking to F# newbies?

**Comment by cloudRoutine** [comment]
@AnthonyLloyd in F# 4.1 it's possible to modify the cexpr to get back to reasonable stack traces
https://eiriktsarpalis.wordpress.com/2016/11/19/reconciling-stacktraces-with-computation-expressions-revisited/

**Comment by AnthonyLloyd** [comment]
Thanks @cloudRoutine it looks good. I guess we can't upgrade to F# 4.1

**Comment by haf** [comment]
Anthony https://travis-ci.org/haf/expecto/jobs/212764632 - Is it perhaps due to running on a single threaded machine?

**Comment by AnthonyLloyd** [comment]
Yes. Or I think I saw they had two procs but high load.

Maybe the test need to check the number of procs and skip if low. Defeats the purpose of the test run in travis though.

I'm stuck on what to do about it. Seems hard to make a reliable deadlock. All solutions like running it for longer and skip for low procs are not great.

**Comment by haf** [comment]
Skipping it if there is not enough concurrency is fine imo

**Comment by AnthonyLloyd** [comment]
I'll add that.

**Comment by haf** [comment]
Excellent!
