### ISSUE TITLE
Update FsCheck's intro to Expecto

### ISSUE THREAD

**Issue by haf** [haf/expecto#117]
https://fscheck.github.io/FsCheck/QuickStart.html#Integration-with-Expecto

to this (and check the last line)

```fsharp
open Expecto

let config = { FsCheckConfig.defaultConfig with maxTest = 10000 }

let properties =
  testList "FsCheck samples" [
    testProperty "Addition is commutative" <| fun a b ->
      a + b = b + a
      
    testProperty "Reverse of reverse of a list is the original list" <|
      fun (xs:list<int>) -> List.rev (List.rev xs) = xs

    // you can also override the FsCheck config
    testPropertyWithConfig config "Product is distributive over addition" <|
      fun a b c ->
        a * (b + c) = a * b + a * c
  ]

Tests.run defaultConfig properties // <-- VERIFY this call
```

Will fix https://github.com/fscheck/FsCheck/issues/349

**Comment by MNie** [comment]
@haf 

![image](https://cloud.githubusercontent.com/assets/7689103/23318817/4a449768-fad4-11e6-9dae-210fe8ef2152.png)

So it should be rather `Tests.runTests defaultConfig properties`?

**Comment by haf** [comment]
@MNie Exactly, that's the overload we need (if it compiles with it).

**Comment by haf** [comment]
I believe I'd already updated this readme.

**Comment by MNie** [comment]
@haf I add this sample to Expecto.Sample project and it seems that everything is ok.

[travis](https://travis-ci.org/MNie/expecto/builds/205095318)
[branch](https://github.com/MNie/expecto/tree/feature/117/add_fscheck_sample)

**Comment by MNie** [comment]
@haf  I think this issue could be closed? Since a fix in Expecto and FsCheck were merged

**Comment by AnthonyLloyd** [comment]
All good I think.
