### ISSUE TITLE
Use a Github Project for expecto->netcore

### ISSUE THREAD

**Issue by adamchester** [haf/expecto#125]
There is now a Github project here: https://github.com/haf/expecto/projects/1. I think we should _try_ to use it for the netcore support. I've never used a Github project before, so I could be totally wrong. It seems like I don't currently have permissions though, hence this issue is being raised.

There are some remaining tasks that aren't easy to manage or track now. There have a been some PRs that were far too big (#101, #123). Some non-trivial tasks are being requested by way of comments in the already huge PRs. The [status was requested](https://github.com/haf/expecto/pull/123#issuecomment-284324935) by a [few people](https://github.com/haf/expecto/pull/123#issuecomment-284239586).

There is a branch now: https://github.com/haf/expecto/tree/netcore

Major tasks are (taken from #101):
 - [x] make CI builds include `donet restore && dotnet build` for `Expecto.netcore`
 - [x] connect AppVeyor to build on PRs
 - [ ] merge the `dotnet pack`ed `netstandard1.6` package into the main nupkg
 - [x] make CI builds run tests against `netstandard1.6` DLL
   - [x] `FSharpx.Core` is not available on netstandard - consider removing it from tests?
   - [x] make `Tests.fs` only use `netstandard1.6` compatible reflection APIs
 - [x] ~do we need old reflection APIs (e.g. `<=net40`)... do we really need `net40` support?~
   - YES - moved to `net45` now
   - [x] make `Expecto.fs` only use `netstandard1.6` compatible reflection APIs
   - [x] make `Expect.fs` only use `netstandard1.6` compatible reflection APIs
 - [X] ~determine what to do with `Mono.Cecil.Rocks` (doesn't exist on `netstandard1.6`?)~
    - Use [`Mono.Cecil 0.10.0-beta2`](https://www.nuget.org/packages/Mono.Cecil/0.10.0-beta2)
 - [x] `Mono.Cecil 0.10.0-beta2` is a semver-prerelease. We cannot release a stable `Expecto` until it is released stable. 

(other tasks I may have forgotten?)

**Comment by haf** [comment]
I think we *can* release a stable version with `paket pack`. Also [it seems to have been fixed now](https://github.com/NuGet/Home/issues/1365#issuecomment-274304485)

**Comment by haf** [comment]
I've given you commit access to the repo for your contributions @adamchester Thank you very much for your continued support. I appreciate the PR-based workflow, even though you could commit directly; even in the future.

**Comment by haf** [comment]
I've added your tasks to the project. You can take it from here.

**Comment by adamchester** [comment]
Thanks @haf 

> I think we can release a stable version with paket pack

Did you mean we can and should release a stable Expecto even though we reference a pre-release package (`Mono.Cecil 0.10.0-beta2`)?

**Comment by enricosada** [comment]
> Did you mean we can and should release a stable Expecto even though we reference a pre-release

there was a bug with `dotnet pack` about that in sdk rc4, but is fixed in rtm. 
So now is not anymore a technical issue.

**Comment by adamchester** [comment]
This is [done](https://github.com/haf/expecto/projects/1).
