### ISSUE TITLE
Test timeout

### ISSUE THREAD

**Issue by vasily-kirichenko** [haf/expecto#135]
Is there a way to set a timeout for a test, test list or test fixture, like `[<Timeout(...)>]` attribute in NUnit?

**Comment by forki** [comment]
Please no attribute. 
But a default combinator would be nice

**Comment by vasily-kirichenko** [comment]
I'd like to set global timeout as well, assembly-wide, in one place.

**Comment by forki** [comment]
Yes that would be a combinator on the run function - or test lists.

**Comment by haf** [comment]
There is, but it's not yet exposed with a top-level function: https://github.com/haf/expecto#sequenced-tests https://github.com/haf/expecto/blob/master/Expecto/Expecto.fs#L376-L392 that takes a `Test`; instead it currently takes a `TestCode` – meaning it's fully possible to *use* it to timeout a test, but not to timeout a list of tests.

As for a total timeout, perhaps a configuration setting around https://github.com/haf/expecto/blob/master/Expecto/Expecto.fs#L1565?

**Comment by haf** [comment]
Closing because this already exists as linked and no reply was given.
