### ISSUE TITLE
Use custom FsCheck Arbitrary in testProperty

### ISSUE THREAD

**Issue by vasily-kirichenko** [haf/expecto#136]
I have this code:
```fsharp
type 'a ClusteredList = ClusteredList of 'a list

let private clusteredListGen =
    gen {
        let! clusterValues = Arb.generate<int> |> Gen.listOf |> Gen.filter (fun x -> x.Length < 10)
        let! res =
            clusterValues
            |> List.map (Gen.constant >> Gen.nonEmptyListOf)
            |> List.fold (fun acc x -> gen {
                 let! acc = acc
                 let! x = x
                 return acc @ x }) 
               (Gen.constant [])
        return ClusteredList res
    } |> Arb.fromGen

testCase "concat = original seq" <| fun _ ->
    let prop (ClusteredList xs) =
        xs |> Seq.groupClusteredBy id id |> Seq.collect snd |> Seq.toList = xs
    Check.QuickThrowOnFailure (Prop.forAll clusteredListGen prop)
```
Is it possible to rewrite it with `testProperty`? I tried:
```fsharp
let private clusteredListConfig = { FsCheckConfig.defaultConfig with arbitrary =  FsCheckConfig.defaultConfig.arbitrary @ [??????] }
testPropertyWithConfig clusteredListConfig "test" <| fun _ -> ...
```
`arbitrary` is a list of `Type`s, I have a value of `Arbitrary<_>` instance. Any ideas how to pass it to config?

**Comment by AnthonyLloyd** [comment]
I use it in the following way if it helps at all:
`
module Gen =
    type Marker = class end
    let config = {FsCheckConfig.defaultConfig with arbitrary = [typeof<Marker>.DeclaringType]}

    let idArb = Arb.convert ID (fun (i:ID) -> i.ToUInt64) Arb.from
    let userIDArb = Arb.convert (string >> User.login) (User.name >> Byte.Parse) Arb.from
    let list1Arb() = Arb.convert (fun (h,t) -> List1.init h t) (fun list -> List1.head list,List1.tail list) Arb.from

... etc ...

[<AutoOpen>]
module Auto =
    let testProp name =
        testPropertyWithConfig Gen.config name
`

Not sure if there is a better way to write the API.

**Comment by haf** [comment]
Anthony is correct; you have to point it out using the config (to avoid tests polluting each other with registered arbitraries in a global static).

@AnthonyLloyd Perhaps by allowing to pass a list of `Arbitrary<'thing>` to the function and just adding that to the config?

Or we could document this better?

**Comment by AnthonyLloyd** [comment]
A list of Arbs may be difficult. For FsCheck config you need a type list or you can use Prop.forAll in the test and create a tuple Arb (http://stackoverflow.com/questions/38839721/how-do-i-implement-multiple-argument-generation-using-fscheck/38841255).

A module of Arbs work for me in the main. I'm not sure how they would override as I've never had to go there and maybe best not to.

I think putting an example in the docs would be very handy as its a bit of trick to get this working well.

**Comment by vasily-kirichenko** [comment]
Yes, I'd like to not pollute global scope with generators. I'd be great if it could be possible to write it like this:
```fsharp
let private myTypeArb : Arbitrary<MyType> = ...

testPropertyWithArbs "test" [myTypeArb] <| fun (x: MyType) -> ...
```

**Comment by AnthonyLloyd** [comment]
Using the approach in the stackoverflow you could do something like:

```fsharp

testPropertyWithArb3 "test" (aArb, bArb, cArb) <| fun (x:a, y:b, z:c) -> ...
```

**Comment by AnthonyLloyd** [comment]
Early days but Hedgehog may be trying to address some of these problems:

http://blog.nikosbaxevanis.com/2017/04/10/less-fragmented-properties-with-hedgehog/

**Comment by haf** [comment]
Meta: I'm not going to contribute to more fragmentation by supporting a library that seemingly doesn't send pull requests towards FsCheck. If it wants to remodel FsCheck then that should be a pull request first, being rejected (like this project was with Fuchu).

On topic: so the only difference there is really `Prop.ForAll` versus `property {}` – because the generators can be used and consumed with a workflow builder in FsCheck as well? That the sample uses operators instead of a workflow builder doesn't change that (but does make the two snippets read very differently)

**Comment by AnthonyLloyd** [comment]
I think they are getting rid of Arbitrary and combining gen and shrink somehow. The docs are very light and just starting to come out so not sure yet if its a new simpler solution.

I agree it should only be considered if its a substantially simpler/better model and FsCheck can't go there.

**Comment by AnthonyLloyd** [comment]
Closing this as Arbitrary is not recommended and won't be support in future FsCheck.

I've added an explanation to the docs and the following issues explain in detail in #201 and  fscheck/FsCheck#413.
