### ISSUE TITLE
Export test results to TeamCity

### ISSUE THREAD

**Issue by vasily-kirichenko** [haf/expecto#138]
I run an exe containing tests with FAKE on TeamCity. If a test fails, TeamCity does not show meaningful info:

![image](https://cloud.githubusercontent.com/assets/873919/24854261/763fc74a-1de6-11e7-941b-405152a0033a.png)

Expecto tests are not presented in tests statistics either.

For example, NUnit test runner produces an XML containing run results, which can be passed to TeamCiyt with a FAKE helper. It would be great to have such workflow for Expecto.

**Comment by haf** [comment]
I'm leaving this open for anybody who uses TC to pick up and work on.

**Comment by vasily-kirichenko** [comment]
What about a new argument `--xmlOutput <path>`? It would be propagated to a new `XmlOutput: string option` field around here https://github.com/haf/expecto/blob/7f558dee6974aa18a29c2cb8c09ffb0abe2022a5/Expecto/Expecto.fs#L825.

I have a Printer already which produces proper NUnit XML in-memory (as XDocument). Where I should hook it? Who should wrote the XML to file? The printer itself?

**Comment by vasily-kirichenko** [comment]
Hmm. Looking at https://github.com/haf/expecto/blob/7f558dee6974aa18a29c2cb8c09ffb0abe2022a5/Expecto/Expecto.fs#L707 it seems it's already implemented (in different way). But I don't see messages like `##teamcity[...` in my TC log. Is this functionality has been released in NuGet?

**Comment by vasily-kirichenko** [comment]
Ah, FAKE runs the test console app as external process, so it does not see TC environment variables :)

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsharp/FAKE/pull/1520
