### ISSUE TITLE
.net core template

### ISSUE THREAD

**Issue by MNie** [haf/expecto#139]
When migration to .net core is done #1 . 
It would be great to have an ability to create an Expecto .net core project by typing:
`dotnet new -i Expecto`
Like it is done for [Fable, Freya and so on.](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new)

CC: @haf

**Comment by MNie** [comment]
Closing since template was created and docs were updated.

**Comment by haf** [comment]
:1st_place_medal:
