### ISSUE TITLE
Question: Why is the message the last argument for all asserts?

### ISSUE THREAD

**Issue by mastoj** [haf/expecto#144]
Is there a good reason to why the message is the last argument? That makes it harder to pipe actual value to an assert like I most often wants to do. I noticed that one of the samples actually did that so I guess that the message hasn't always been the last argument.

**Comment by MNie** [comment]
@mastoj There is also [Flip module](https://github.com/haf/expecto/blob/master/Expecto/Flip.Expect.fs) created for pipes. Do you try this one?

[There](https://github.com/haf/expecto/blob/master/Expecto.Sample/Expecto.Flip.Sample.fs) are some samples.
[Here](https://github.com/haf/expecto/pull/119) is an issue with Flip module.

**Comment by mastoj** [comment]
I'll definitely try that instead of writing my own helpers :)

**Comment by mastoj** [comment]
Closing since this was a question and I'm satisfied with the answer.
