### ISSUE TITLE
Strange characters when running expecto's template project

### ISSUE THREAD

**Issue by Kurren123** [haf/expecto#145]
# Steps to reproduce

Go to a new folder

```
dotnet new -i Expecto.Template::5.0.0-beta1
dotnet new expecto
dotnet restore
dotnet build
dotnet run
```

# Output

Strange characters are next to the last line:

[11:05:37 INF] EXPECTO! 8 tests run in 00:00:00.2364089 ÔÇô 2 passed, 1 ignored, 5 failed, 0 errored. ( Ó▓░ ─╣╠» Ó▓░Ó│â )

Screenshot:

![image](https://cloud.githubusercontent.com/assets/3525980/25380185/4668b41a-29a7-11e7-8eab-afd29509a94e.png)

# System info

-  Windows 10
- Dotnet version 1.0.0

**Comment by forki** [comment]
@haf calls that "spirit" and it's supposed to be something like an emoji / smiley. Unfortunately it often just looks weird. I tried to PR it out but @haf insisted it stays ;-(

**Comment by MNie** [comment]
@Kurren123 it's a rather problem with encoding/font in your cmd? 
@forki It's related to Expecto.Template I could remove this emoji / smiley from [Expecto.Template samples file](https://github.com/MNie/Expecto.Template/blob/master/Sample.fs).

**Comment by vasily-kirichenko** [comment]
I'm also for removing this unicode noise. If not @forki I'd never recognized a smile there.

**Comment by Kurren123** [comment]
@MNie i don't think its related to the template because when I replace the tests with my own simple test I still get the issue

**Comment by forki** [comment]
@MNie no the template is unrelated nonsense ;-)

**Comment by Kurren123** [comment]
@MNie Is this a problem with my specific cmd? I'm guessing you can see the smiley on linux but not windows

**Comment by forki** [comment]
@Kurren123 yes there are situations where the console shows the intended chars, but even then some peope (like me) can't see that it is supposed to be a smiley.

**Comment by MNie** [comment]
`@MNie no the template is unrelated nonsense ;-)`
@forki I looked at first at steps to reproduce my mistake ;)

**Comment by forki** [comment]
@MNie I was obviously joking a bit, but I'd prefer we remove spritis from templates and product

**Comment by haf** [comment]
@Kurren123 There are UTF8 capable terminals in the world, even on Windows. The spirit is this one:

"ᕙ໒( ˵ ಠ ╭͜ʖ╮ ಠೃ ˵ )७ᕗ"

**Comment by forki** [comment]
doesn't look any different to me.

**Comment by haf** [comment]
There are arms at the start and end and a monocle on the right eye?

**Comment by forki** [comment]
and a bit of snot in the nose?

**Comment by Kurren123** [comment]
@haf yes the command prompt is pretty basic so it's a good idea to use something else. However the same bug appears on the terminal within vscode also: 

![image](https://cloud.githubusercontent.com/assets/3525980/25388105/c6c7f7d4-29c4-11e7-8e46-a6bc709243f4.png)

I actually like the smiley, it's just the jumbled characters that look messy

**Comment by haf** [comment]
@Kurrren123 – that's a bug in VSCode and/or the terminal emulator it uses.

**Comment by adamchester** [comment]
I haven't dug into this yet, this recent change might be related https://github.com/haf/expecto/commit/bc3a172415869d2ba7aad0beed073587258d78d0#diff-312b950ecb6e71200586b2408ab6e821R643
