### ISSUE TITLE
The primary reference "Expecto" could not be resolved

### ISSUE THREAD

**Issue by vbfox** [haf/expecto#151]
Expecto is currently present in a `net40` folder in it's nuget package suggesting a 4.0+ compatibility but it isn't the case as installing it in any version < 4.6.1 fails with :

    warning MSB3274: The primary reference "Expecto" could not be resolved because it was built against the ".NETFramework,Version=v4.6.1" framework.
        This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2"

Tested on expecto 4.2.1.

**Comment by haf** [comment]
Yes I know. Please see https://github.com/Albacore/albacore/issues/148

**Comment by sergey-tihon** [comment]
Does it mean that Expecto will not work on .net `<4.6.1` when issue will be fixed?

**Comment by haf** [comment]
Right. Expecting targets 4.6.1 because that has the most overlap with net core afaik.

**Comment by forki** [comment]
ping. We currrently have a nuget package that says it works for net40 but doesn't can you please push a fix?

**Comment by haf** [comment]
No, I haven't fixed the bug yet, so I can't. But it's clearly documented how to fix it if you want to fix it. Sorry.

**Comment by 7sharp9** [comment]
Where is it clearly documented on how to fix?

**Comment by haf** [comment]
here https://github.com/Albacore/albacore/issues/148

**Comment by haf** [comment]
v2.7.0 has been released of albacore thanks to @danieljsummers – it's now possible to bump the dependency here until #175 lands.

**Comment by haf** [comment]
Upgraded albacore, doing a test build now.

**Comment by haf** [comment]
<img width="782" alt="screen shot 2017-06-17 at 11 02 46" src="https://user-images.githubusercontent.com/193115/27251706-a608413c-534c-11e7-8043-00b165fef1be.png">

**Comment by haf** [comment]
Ok, let's go for release v5.0 then!
