### ISSUE TITLE
Expect.all and Expect.exists

### ISSUE THREAD

**Issue by haf** [haf/expecto#156]
```
allEqual: actual:#seq<'thing> -> thing:'thing -> message:string
all: actual:#seq<'thing> -> asserter:('thing -> bool) -> message:string
exists: actual:#seq<'thing> -> asserter:('thing -> bool) -> message:string
```

 - [x] allEqual
 - [x] all
 - [x] exists
 - [x] Expect.Flip
 - [x] Update README with docs on the above
 - [x] XMLDOC above each function
 - [x] Specify in the failure message, what iteration count you failed at, what the last seen item was and call/print a stubbed delta/diff function on the `'thing`, printing what differs between the expected and the found (that returns `false` from the `asserter`)

With "stubbed diff function", I mean a structural comparison, similar to what #6 would check for, but for a single object/type.

Example usage with Expect.Flip opened:

<img width="503" alt="screen shot 2017-05-11 at 10 39 54" src="https://cloud.githubusercontent.com/assets/193115/25940365/379dded8-3636-11e7-8d21-590ab4dd0d92.png">

**Comment by haf** [comment]
Ping @gentauro and @MNie – if you're interested ;)

**Comment by MNie** [comment]
@haf I could do that. I will provide pr with that tommorow if it's not a problem :)

**Comment by haf** [comment]
Done! Thanks to MNie
