### ISSUE TITLE
FakeHelper

### ISSUE THREAD

**Issue by vilinski** [haf/expecto#16]
Hi, great and simple testing library. 
Currently I have make-it-done-solution like above. But may be is there any FAKEHelper which I have overlooked? 

```fsharp
Target "RunExpectoTests" (fun _ ->
    let processTimeout = System.TimeSpan.MaxValue // Don't set a process timeout.  The timeout is per test.
    let testsAssemblies = "build/*Tests.exe"
    let args = [ "--debug"
                 //"--sequenced"
                 "--parallel"
               ] |> String.concat " "
    let res = 
        !! testsAssemblies
        |> Seq.map (fun testAssembly -> 
            testAssembly, ExecProcess(fun info ->
                info.FileName <- testAssembly
                info.WorkingDirectory <- buildDir
                info.Arguments <- args
            ) processTimeout)
        |> Seq.filter( snd >> (<>) 0)
        |> Seq.toList
    match res with
    | [] -> ()
    | failed -> 
        failed
        |> List.map (fun (asm,exitCode) -> sprintf "\t- Expecto test %s failed. Process finished with exit code %d." asm exitCode)
        |> String.concat System.Environment.NewLine 
        |> FailedTestsException |> raise
)
```

**Comment by forki** [comment]
I think this should be opened in FAKE repo. And maybe you are interested in contributing such a helper over there.

**Comment by vilinski** [comment]
my PR https://github.com/fsharp/FAKE/pull/1435

**Comment by forki** [comment]
this is released in FAKE 4.47, but I noticed a glitch in timing report:

![image](https://cloud.githubusercontent.com/assets/57396/21287056/b1109f3e-c463-11e6-8ef4-8669c60c8b2c.png)

**Comment by haf** [comment]
There's a console semaphore you'll have to take a lock on unless you want intertwined outputs. I don't know the char that's printed in a funky manner before `1 passed`.

**Comment by forki** [comment]
fake helper is released. this can be closed
