### ISSUE TITLE
--summary flag replaces TeamCity printer with default printer

### ISSUE THREAD

**Issue by jindraivanek** [haf/expecto#162]
With --summary flag TeamCity printer don't work, even if its added to config with `{ defaultConfig with printer = Expecto.Impl.TestPrinters.teamCityPrinter defaultConfig.printer }`. 

Guessing from this code https://github.com/haf/expecto/blob/master/Expecto/Expecto.fs#L1505, it will also happen for --summary-location and --stress flags and these flags replace any custom printer with default printer.

**Comment by haf** [comment]
Yeah; so we have a case of printers 'overwriting each other's settings'. I can think of two solutions:

 - `--multi-printer` – composes all printers together, but makes it impossible to replace the default printe
 - `--printers "teamcity,default"` – naming the printers and making an argument case: `Printers of printers:string[]` in the DU of allowed arguments, then amending the code correspondingly.

I'll let you PR what you feel is the best solution.

**Comment by jindraivanek** [comment]
I am thinking about solution where each non-default printer get inner printer as a parameter and alter it (instead of altering default printer). Does this sound good?

**Comment by haf** [comment]
No that's not composable. Better then to have a fan-out printer

**Comment by jindraivanek** [comment]
OK, I think I need to be more detailed here, because adding new option doesn't solve the issue:

#### What is the issue?

--summary flag replaces printer with default printer and that is IMO unexpected behavior and confusing. (I spent hour or so debugging this, because I thought problem was with the environment variable.)

#### What is the expected behavior?

--summary flag should only produce extra output at the end of tests and don't alter rest of the output.

Do we have an agreement on this?

**Comment by haf** [comment]
Yes, that we agree on =)

**Comment by jindraivanek** [comment]
Good :)

So, most simple solution is change summary printer to something like this:
```fsharp
static member summaryPrinter innerPrinter =
      { innerPrinter with
          summary = fun config summary -> 
            TestPrinters.defaultPrinter.summary config summary // or innerPrinter.summary?
            |> Async.bind (fun () -> logSummary summary) }
```

and for --summary flag, call it with config.printer

I think this should fix the issue. 

I understand composability concerns, but that's IMO another issue/feature (to rewrite printers in composable manner).

**Comment by haf** [comment]
Yes, that's approaching a solution. Inner printer is the composition I'm looking for. But doesn't your solution make the fold of arguments, position-dependent?
