### ISSUE TITLE
Problems with Ionide in VS Code

### ISSUE THREAD

**Issue by SirEel** [haf/expecto#176]
I'm having trouble with Expecto in Ionide with VSCode. I created Expecto project from command console. First it wouldn't build, because .fsproj was targeting .NET 4.5 and Expecto was built with 4.6.1. I changed version to 4.6.1 in .fsproj, now it builds, and I can run my tests from external command window. But (1) Intellisense in the VSCode editor gives red squiggles wherever Expecto is mentioned, starting with "Open Expecto"; and (2) if I run Expecto:Run from command console, I see no output in the Expecto Output window.
Environment:
VSCode 1.13.0
Ionide 2.26.1
Window 10

**Comment by haf** [comment]
I've "forwarded" this issue to ionide.
