### ISSUE TITLE
Test Results file.

### ISSUE THREAD

**Issue by donovanlange** [haf/expecto#179]
For projects using VSTS as their CI system, it'd be really amazing if Expecto could optionally (via a command line parameter) generate a TestResults file in an NCrunch or XUnit compatible XML format (a la: https://www.visualstudio.com/en-us/docs/build/steps/test/publish-test-results)...

I realize that as I'm asking for this, that of course a free pony would be amazing, too.  But to the extent that it was on someone's radar as well, I figured it worth tracking.  :)

Thanks!

**Comment by adamchester** [comment]
FYI there is also this: https://github.com/adamchester/expecto-adapter

The adapter can plug in to VSTS, and publish test results, but right now it has fallen a little behind Expecto itself, and has a few serious bugs (help welcome!).

**Comment by donovanlange** [comment]
@adamchester: Yeah, I had actually given it a try, but had some issues.

(In fairness, not sure if it was on my side -- as we're doing some funky things in our build environment -- or if it was the fact that we were building an Exe output, or not setting the right platform, etc.  The net result was that mstest.exe was never finding any of our tests.  :()

Ultimately, I ended up turning my attention elsewhere in the short term, but may give it another run soon.

**Comment by AnthonyLloyd** [comment]
If you do this it could be used for 2 other uses that I'd happy to help with:

1) Use the last run stats to order the parallel so big tests are started first.
2) Check if an test is taking significantly longer than the previous run.

**Comment by haf** [comment]
@AnthonyLloyd Those are great ideas. It would be nice to have these full concepts as a clear .net interface with a default implementation on-disk – but with other implementations for stateless build systems like travis, appveyor, gcloud build etc.

**Comment by haf** [comment]
@matthid From missing files on disk?

**Comment by matthid** [comment]
It's basically about using your test results and processing them further in your pipeline. Most test frameworks output more or less standardized files for this.

You can do analysis like "this test fails often" or something like that. Things you cannot do if you throw your results away on every build. 
It's also about integration in existing systems for nice UI.

**Comment by matthid** [comment]
after looking at this, It's actually not that hard to add:

```fsharp

[<EntryPoint>]
let main argv =
    Logging.init()
    let writeXmlFile = writeNUnitSummary "ResultNUnit.xml"
    let testConfig =
        { defaultConfig with
            parallel = false
            printer = withSummaryHandler writeXmlFile defaultConfig.printer }

    Tests.runTestsInAssembly testConfig argv
```

With the following:


```fsharp

let writeNUnitSummary file (summary: Impl.TestRunSummary) =
    // v3: https://github.com/nunit/docs/wiki/Test-Result-XML-Format
    // this impl is v2: http://nunit.org/docs/files/TestResult.xml
    let testCaseElements =
        summary.errored @ summary.failed @ summary.ignored @ summary.passed
        |> Seq.map (fun (flatTest, test) ->
            let content =
                match test.result with
                | Impl.TestResult.Passed ->[|
                    XAttribute(XName.Get "executed", "True") |> box
                    XAttribute(XName.Get "result", "Success") |> box
                    XAttribute(XName.Get "success", "True") |> box
                    XAttribute(XName.Get "time",
                        System.String.Format(System.Globalization.CultureInfo.InvariantCulture,
                            "{0:0.00}", test.duration.TotalSeconds)) |> box
                    XAttribute(XName.Get "asserts", "0") |> box
                    |]
                | Impl.TestResult.Error e -> [|
                    XAttribute(XName.Get "executed", "True") |> box
                    XAttribute(XName.Get "result", "Failure") |> box
                    XAttribute(XName.Get "success", "False") |> box
                    XAttribute(XName.Get "time",
                        System.String.Format(System.Globalization.CultureInfo.InvariantCulture,
                            "{0:0.00}", test.duration.TotalSeconds)) |> box
                    XAttribute(XName.Get "asserts", "0") |> box
                    XElement(XName.Get "failure", [|
                        XElement(XName.Get "message", e.Message)
                        XElement(XName.Get "stack-trace", e.ToString())
                        |]) |> box
                    |]
                | Impl.TestResult.Failed msg-> [|
                    XAttribute(XName.Get "executed", "True") |> box
                    XAttribute(XName.Get "result", "Failure") |> box
                    XAttribute(XName.Get "success", "False") |> box
                    XAttribute(XName.Get "time",
                        System.String.Format(System.Globalization.CultureInfo.InvariantCulture,
                            "{0:0.00}", test.duration.TotalSeconds)) |> box
                    XAttribute(XName.Get "asserts", "0") |> box
                    XElement(XName.Get "failure",
                        XElement(XName.Get "message", msg)) |> box
                    |]
                | Impl.TestResult.Ignored msg -> [|
                    XAttribute(XName.Get "executed", "False") |> box
                    XAttribute(XName.Get "result", "Ignored") |> box
                    XElement(XName.Get "reason",
                        XElement(XName.Get "message", msg)) |> box
                    |]

            XElement(XName.Get "test-case", [|
                yield XAttribute(XName.Get "name", flatTest.name) |> box
                yield! content
            |]))
    let element = XElement(XName.Get "test-run", [|
        yield XElement(XName.Get "test-suite", [|
            yield XElement(XName.Get "results", [|
                yield! testCaseElements
            |]) |> box
          |]) |> box
    |])

    let path = Path.GetFullPath file
    let doc = XDocument([|element|])
    doc.Save(path)
    ()

let withSummaryHandler handleSummary (def: Expecto.Impl.TestPrinters) =
    { def with
        summary = fun _config summary -> async {
            do! def.summary _config summary
            handleSummary summary
          }
      }
```

I have not tested it in detail but it seems to work rudimentary.

**Comment by haf** [comment]
@matthid Do you know that FAKE crashes iTerm sometimes?

**Comment by haf** [comment]
https://github.com/haf/expecto/releases/tag/8.3.0

**Comment by haf** [comment]
https://github.com/haf/expecto#testresults-file

**Comment by matthid** [comment]
@haf thanks for taking care of this would have taken me a while to come up with a PR. Also your API looks a bit better ;)

Regarding the fake crash: I never heard it but please open an issue maybe it it reproducible with a while loop and a small script?

**Comment by haf** [comment]
@matthid NP, thank you for your contribution!

I think it's iTerm+zsh that's buggy; a colleague just got a crash running a simple shell script... I redirected to file and that allowed me to release without crashing.

**Comment by JonCanning** [comment]
🎉

Is there an Expecto.TestResults package?

**Comment by haf** [comment]
@JonCanning Yes https://www.nuget.org/packages/Expecto.TestResults

**Comment by matthid** [comment]
Well at least it does import to VSTS. So that is good. I don't know how strictly this schema is enforced across build system.

**Comment by haf** [comment]
Feels a bit hacky to output downright invalid data; we're not nunit...
