### ISSUE TITLE
Decouple assertions and tests

### ISSUE THREAD

**Issue by ploeh** [haf/expecto#181]
Hi

Sorry to be writing like this out of the blue, but I'd been working on an F#-based test runner similar to Expecto for a while, and never really gotten anywhere with it, and then I ran into Expecto. It seems to be doing pretty much what I'd like an automated testing library to do. The fact that I never really got anywhere with my own project, while this is now almost at version 5, I can only interpret as an indication that you're better F# programmers than I am 👍

I'd like to help promulgating the message of tests as first-class values, and also, perhaps, if time allows, help with a bit of code now and then. Perhaps even some documentation 😄 (FWIW, as an example, I've written a decent bit of FsCheck's [Generating test data](https://fscheck.github.io/FsCheck/TestData.html) page).

There is, however, one major blocker for me in the current Expecto library. You may think that this is terribly irrational of me, but I dislike the fact that Expecto includes an assertion library (the `Expect` module). Tests and assertions are two separate concerns.

xUnit.net split off their assertion library in version 2.0 for this reason. This is one of several reasons I currently prefer xUnit.net over other libraries; I get to choose an assertion library of my own choice (Unquote).

If Expecto would decouple assertions from tests, this could tip the scale for me, making me prefer Expecto over xUnit.net.

It could be done in the same way that xUnit.net does it: the `Expecto` package could remain as it is now, but underneath, it would consist of two dependent packages, `Expecto.Assertion` and `Expecto.Test`, or something to that effect. Thus, it might not even need to be a breaking change.

One counter-argument that I can already predict is: _can't you use Expecto and simply ignore the `Expect` module?_ Yes, I can do that if I'm working by myself, but if I'm in a team, then I'd need to explain to other team members why they should use e.g. Unquote instead of the built-in module, and I'd need to constantly police the code base to ensure that assertions are written according to policy. That's a problem I don't think I ought to have.

If my suggestion of creating two separate libraries is welcome, I don't mind sending a pull request, but I'd like to ask before I do any work.

**Comment by haf** [comment]
Hi @ploeh and welcome to Expecto.

I can't answer for the other contributors, but for me, I want to have a dialectical discussion before I say either yes or no to architecture ideas. Please take the questions only as a quest for clearer thinking.

You say that having an assertion library is a drawback because it conflates concerns. But then surely logging of output is also a conflated concern? Especially as other topics (#179) are discussing including infrastructure for persistent test results as basis for comparison with current results?

Further, is it not a drawback that beyond adding a ref to Expecto, you also have to reference its assertion library in your fsx files (if that's your workflow)? Doesn't it go against the principle of least surprise? On the same topic, is the value of "the known" not greater than the value of principled usage of an assertion library?

The last question then; if we can move towards structurally intact Message/Assert values flowing upwards, wouldn't the assertion library in use be a moot point, as they'd all be adopting the interface of the messages?

**Comment by ploeh** [comment]
I'm not sure how to respond to this. I tried cloning the repository, but I can't get it to build. I can't figure out exactly what `Expecto.Logging` does, so I can't respond to that part. If I understand #179 correctly, I'd most certainly consider it a separate issue that has no place in a core library.

The next paragraph, I can't parse...

You can often pick an attractive metaphor, but _batteries included_ implies, to me, that I'd be dealing with a framework instead of a library, and for [the reasons explained by Tomas Petricek](http://tomasp.net/blog/2015/library-frameworks), I prefer to avoid frameworks. If you want to stick with the metaphor, I don't like things that run on batteries, as they are not durable; often, I prefer to plug in a power source of my own choice. I can't easily do that if the batteries are integrated in the product.

**Comment by haf** [comment]
Logging docs are here: https://github.com/haf/expecto#about-test-parallelism

> which is discussing the inclusion of infrastructure for persistent test results as basis for comparison with current results?

...which is about creating a saver for test results. Subsequent runs will have their results compared to the persisted results.

Expecto doesn't match "It defines some extensibility points (interfaces) where you need to put your implementation.", so it's not a framework then.

That said, the pattern of interfaces is not a bad one, since it is also used for composing the behaviour of stand-alone components that are composed and invoked as opposed to configured and invoking your code.

**Comment by haf** [comment]
What do you think, contributors? Make assertions separate? @teo-tsirpanis @mnie @enricosada @ronniebarker @adamchester @mtnrbq?

**Comment by adamchester** [comment]
I think keeping assertions separate is an attractive idea for all the reasons @ploeh gives. I too use Xunit with different assertion libraries. I love the fact that you don't need to justify or explain this concept to teams because people usually realise it's a deliberate feature.

I must also admit I'm looking forward to having even more colourful console output from both the assertions and the discovery/execution engine so that reading the output is easier and more productive, I hope we can take that into consideration if we split them.

**Comment by enricosada** [comment]
Adding difference assetions libs is a recurring topic and make sense as the test library grow and is used in more scenario ( I too like a lot unquote for assertions ).

> It could be done in the same way that xUnit.net does it: the `Expecto` package could remain as it is now, but underneath, it would consist of two dependent packages, `Expecto.Assertion` and `Expecto.Test`, or something to that effect. Thus, it might not even need to be a breaking change.

Seems ok.
by default `open Expecto` get both (installed is `Excepto` nupkg). 
to opt-out, with specific assertion lib is `open Expecto.Test` + `open Swensen.Unquote` (installed is `Expecto.Test` nupkg)


> but batteries included implies, to me, that I'd be dealing with a framework instead of a library

Depends. `FSharp.Core` is batteries included (lots of function for lots of special cases), but is not a fw.

**Comment by haf** [comment]
Seems like we're all in agreement. @ploeh

**Comment by teo-tsirpanis** [comment]
Well, @ploeh's idea is interesting.

Xunit has a simple foolproof package, surprisingly called `xunit` (oh, really? 😛). The users who want to _just_ use it, reference this package, and it does the dirty work for us.

Having the `Expecto` package decoupled, allows the developers to mix and match testing and asserting libraries. Some parts of Expecto are already decoupled, so why not progress this decoupling even more? Of course, backwards compatibility must be preserved, as it could be implemented in a future `5.1.0` release.

**Comment by haf** [comment]
So @ploeh, you seem to have a green light!

**Comment by ploeh** [comment]
That's great 👍 It may take me a week or two before I have time to circle back to this, but I've put it on my explicit to-do list.

**Comment by haf** [comment]
Hi there @ploeh !

**Comment by ploeh** [comment]
Sorry I disappeared for so long, but I had other things to attend to, and I had to find a system that could fit all the requirements for a development environment...

I've now updated my Ruby environment, installed Albacore, installed the .NET Core SDK, and so on. To be honest, I don't find that running `build.sh` is conclusive, though. It basically just stops running after minutes of text scrolling by, and the last it prints is this:

```
        stress testing/sequenced group
        stress testing/two sequenced groups
        stress testing/never ending
        stress testing/never ending sequenced
Ignored:   2
        performance/same function is faster should fail
        all focused tests/ignored by attribute
Failed:    2
        focused
        config
Errored:   0 <Expecto>
C:/Users/mark/Desktop/expecto/Rakefile:110:in `block (2 levels) in <top (required)>'
Tasks: TOP => default => tests => tests:unit
(See full trace by running task with --trace)
```

Is that a build failure? If so, why?

**Comment by teo-tsirpanis** [comment]
I don't know. I did not modify any test code.

**Comment by haf** [comment]
@ploeh You'll find that it's been moved from a ruby based build now

**Comment by AnthonyLloyd** [comment]
The failed focused & config tests were a line ending thing between git and windows. I've normalized all files to LF and added a .gitattributes to always convert to LF and never convert back so hopefully we won't see this again.

**Comment by ploeh** [comment]
I'm currently giving this a shot, but I need a little help, as I'm completely ignorant of how .NET Core works.

I've noticed that some projects have a corresponding `.netcore.fsproj` file. As far as I can tell, these project files are used to build .NET Core versions of the various packages. Looking at their contents, they're just XML files like other `fsproj` files, so clearly I could edit them by hand, but before I do that, I'd like to ask:

_What's the intended workflow with such files? Am I supposed to add and edit them by hand, or is there some sort of tool I should invoke?_

I don't mind hand-editing, but if there's a more appropriate way to do this, I should do that instead.

**Comment by AnthonyLloyd** [comment]
At the moment we are just making the .netcore ones match the the VS ones by hand in the XML. We are actually building all the packages from the .netcore now.

I want to move to just having only the .netcore in a VS solution. We are close to this. I'm going to have a look at it tomorrow night. This may mean VS has to be 2017 with latest updates from then on.

**Comment by AnthonyLloyd** [comment]
I've added Expecto.netcore.sln which contains the netcore projects. I have the sample and C# to add.

This can be used from VS2017 and you get new style solution explorer & project reference but the best code edit experience is still VS Code.

I'd like to ditch the old sln and projs but I'm worried it may be a bit too soon. Will add the other projects and see how we go.

For now to add new code files this will have to be done in both types of projects to make sure all builds pass. Let me know if you run into problems with this.

**Comment by ploeh** [comment]
OK, I give up on this. It's not your fault, but I spent most of yesterday fighting with all sorts of build errors. Either I have no idea what I'm doing, or the combination of F#, .NET Core, and VS 2017 is still too immature.

Anyways, I don't feel like starting over.

If you rely on me to address this issue, you can close it.

Sorry 😟

**Comment by enricosada** [comment]
@AnthonyLloyd as an unwanted feedback, dont put old sdk fsproj and new fsproj in same directory. that's going to mess a bit, because they both use the `obj` dir, but in different way.
split these in other directories, and use relative paths in `Compile` items.

**Comment by enricosada** [comment]
@ploeh if you need help with netcore, ping me. happy to help with that.
usually things works, maybe better in VScode/rider than VS, but that should work too.

**Comment by AnthonyLloyd** [comment]
@enricosada Thanks. I may have seen some of that already.

I'm thinking of moving quickly to just the netcore ones now everything is packaged from them. Do you think this a good/bad idea? I think means only very latest VS2017 can be used.

**Comment by AnthonyLloyd** [comment]
@ploeh No worries. I'll keep this open and add help wanted. Hopefully we can simplify to just netcore and VS tooling gets there soon.

**Comment by AnthonyLloyd** [comment]
Did the reduction down to just dotnet core projects and one solution. Should simplify things going forward.
