### ISSUE TITLE
Question 4.x vs 5.x

### ISSUE THREAD

**Issue by jon49** [haf/expecto#182]
I don't have VS 2017 yet and didn't want to purchase it yet. It appears 5.x doesn't work on VS 2015. Will 4.x still be supported or has it been deprecated? I brought up the library in VS Code for 5.x but the learning curve is a bit steep (I'm used to the full power of VS). If 4.x isn't supported I guess I'll try and take the plunge into VS Code, I just wanted to get this work done fast rather than have to learn yet another tool on top of `Expecto`.

Thanks!

**Comment by haf** [comment]
Hi,

Perhaps you were thinking filing this issue in https://github.com/adamchester/expecto-adapter?

I don't use Visual Studio.

Regards

**Comment by jon49** [comment]
OK, I'll take it that 4.x isn't being supported anymore than. I guess I'll try and learn VS Code or purchase VS 2017 (if I can talk my boss into it - I was going to wait until service pack 1 first but I guess not :-) )!

Thanks!

**Comment by haf** [comment]
@jon49 All my current projects are on 4.x and it's only just 5 days ago that v5 was released; v4 has run successfully in VS a long time now. I don't know what version thereof, though. You could ask in the right repo about that ;)

**Comment by jon49** [comment]
Thanks for your help and all your work on all the projects! I took the plunge into VS Code and got it working nicely. Not as nice Vim emulation support but not too bad.

So, I'm working with 5.x now. I didn't know 5.x was released so recently!
