### ISSUE TITLE
Expecto version 5 - Installation failed .net 4.5.2

### ISSUE THREAD

**Issue by rodrigovidal** [haf/expecto#187]
![image](https://user-images.githubusercontent.com/388081/28184281-0a2a53be-6813-11e7-81d2-febd3308a439.png)

Hi I'm getting the error above when I try to install Expecto via nuget in a .net 4.5.2 project.

Any ideas?

**Comment by rodrigovidal** [comment]
Expecto 4.2.1 works fine.

**Comment by haf** [comment]
It requires 4.6.1 from v5 onwards.

**Comment by rodrigovidal** [comment]
@haf Thanks!
