### ISSUE TITLE
Can't install from nuget

### ISSUE THREAD

**Issue by giuliohome** [haf/expecto#188]
I'm using Visual Studio Community edition and I'm creating a simple F# Console appl.
When I try to install Expecto from NuGet Package Manager, it fails with

`
Attempting to gather dependency information for package 'Expecto.5.0.0' with respect to project 'IllegalDataUnrepresentable', targeting '.NETFramework,Version=v4.0'
Gathering dependency information took 1,69 sec
Attempting to resolve dependencies for package 'Expecto.5.0.0' with DependencyBehavior 'Lowest'
Unable to find a version of 'Mono.Cecil' that is compatible with 'Expecto 5.0.0 constraint: Mono.Cecil (>= 0.10.0-beta5)'.
========== Finished ==========
Time Elapsed: 00:00:01.8725801`

**Comment by forki** [comment]
Try to use a different target framework. Expecto doesn't work for net40.
Try net462

Am 23.07.2017 1:30 vorm. schrieb "giuliohome" <notifications@github.com>:

**Comment by giuliohome** [comment]
I tried also net461 and it didn't work. Now I've installed the dev pack for net462 as per your suggestion and this is the result again

> Attempting to gather dependency information for package 'Expecto.5.0.0' with respect to project 'IllegalDataUnrepresentable', targeting '.NETFramework,Version=v4.6.2'
> Gathering dependency information took 2,09 sec
> Attempting to resolve dependencies for package 'Expecto.5.0.0' with DependencyBehavior 'Lowest'
> Unable to find a version of 'Mono.Cecil' that is compatible with 'Expecto 5.0.0 constraint: Mono.Cecil (>= 0.10.0-beta5)'.
> ========== Finished ==========
> Time Elapsed: 00:00:04.7527004
>

**Comment by forki** [comment]
Mhm then I'm out of ideas and it might be a nuget bug. 
Did you try with paket?

**Comment by MNie** [comment]
@giuliohome  the problem is with beta version of mono.cecil:
`Unable to find a version of 'Mono.Cecil' that is compatible with 'Expecto 5.0.0 constraint: Mono.Cecil (>= 0.10.0-beta5)'.`
If you try to install Expecto via
`Install-Package Expecto -pre` 
instead of 
`Install-Package Expecto` 
everything should be fine.
![image](https://user-images.githubusercontent.com/7689103/28498906-64bf8298-6fa9-11e7-836b-f861000a6649.png)

**Comment by giuliohome** [comment]
@MNie Thank you!!! 

I'm still getting an exception (H`RESULT: 0x80004005 (E_FAIL)`), but I hope it's fine anyway.

```
PM> Install-Package Expecto -pre


Attempting to gather dependency information for package 'Expecto.5.0.0' with respect to project 'IllegalDataUnrepresentable', targeting '.NETFramework,Version=v4.6.2'
Gathering dependency information took 1,96 sec
Attempting to resolve dependencies for package 'Expecto.5.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Expecto.5.0.0'
Resolved actions to install package 'Expecto.5.0.0'
Retrieving package 'Mono.Cecil 0.10.0-beta5' from 'nuget.org'.
Retrieving package 'Argu 3.7.0' from 'nuget.org'.
Retrieving package 'FSharp.Core 4.1.17' from 'nuget.org'.
Retrieving package 'System.ValueTuple 4.3.0' from 'nuget.org'.
Retrieving package 'Expecto 5.0.0' from 'nuget.org'.
  GET https://www.nuget.org/api/v2/package/Expecto/5.0.0
  GET https://www.nuget.org/api/v2/package/Mono.Cecil/0.10.0-beta5
  GET https://www.nuget.org/api/v2/package/Argu/3.7.0
  OK https://www.nuget.org/api/v2/package/Argu/3.7.0 681ms
Installing Argu 3.7.0.
  OK https://www.nuget.org/api/v2/package/Expecto/5.0.0 1220ms
Installing Expecto 5.0.0.
  OK https://www.nuget.org/api/v2/package/Mono.Cecil/0.10.0-beta5 1275ms
Installing Mono.Cecil 0.10.0-beta5.
Adding package 'Argu.3.7.0' to folder 'C:\dev\SO\FSharp\Typing\IllegalDataUnrepresentable\packages'
Added package 'Argu.3.7.0' to folder 'C:\dev\SO\FSharp\Typing\IllegalDataUnrepresentable\packages'
Added package 'Argu.3.7.0' to 'packages.config'
Successfully installed 'Argu 3.7.0' to IllegalDataUnrepresentable
Adding package 'Mono.Cecil.0.10.0-beta5' to folder 'C:\dev\SO\FSharp\Typing\IllegalDataUnrepresentable\packages'
Added package 'Mono.Cecil.0.10.0-beta5' to folder 'C:\dev\SO\FSharp\Typing\IllegalDataUnrepresentable\packages'
Added package 'Mono.Cecil.0.10.0-beta5' to 'packages.config'
Successfully installed 'Mono.Cecil 0.10.0-beta5' to IllegalDataUnrepresentable
Adding package 'System.ValueTuple.4.3.0' to folder 'C:\dev\SO\FSharp\Typing\IllegalDataUnrepresentable\packages'
Added package 'System.ValueTuple.4.3.0' to folder 'C:\dev\SO\FSharp\Typing\IllegalDataUnrepresentable\packages'
Added package 'System.ValueTuple.4.3.0' to 'packages.config'
Successfully installed 'System.ValueTuple 4.3.0' to IllegalDataUnrepresentable
Adding package 'FSharp.Core.4.1.17' to folder 'C:\dev\SO\FSharp\Typing\IllegalDataUnrepresentable\packages'
Added package 'FSharp.Core.4.1.17' to folder 'C:\dev\SO\FSharp\Typing\IllegalDataUnrepresentable\packages'
Errore non specificato. (Eccezione da HRESULT: 0x80004005 (E_FAIL))
Added package 'FSharp.Core.4.1.17' to 'packages.config'
Successfully installed 'FSharp.Core 4.1.17' to IllegalDataUnrepresentable
Adding package 'Expecto.5.0.0' to folder 'C:\dev\SO\FSharp\Typing\IllegalDataUnrepresentable\packages'
Added package 'Expecto.5.0.0' to folder 'C:\dev\SO\FSharp\Typing\IllegalDataUnrepresentable\packages'
Added package 'Expecto.5.0.0' to 'packages.config'
Successfully installed 'Expecto 5.0.0' to IllegalDataUnrepresentable
Executing nuget actions took 20,19 sec
Time Elapsed: 00:00:30.5054732
```

**Comment by MNie** [comment]
@giuliohome  You're welcome :)
