### ISSUE TITLE
NETStandard project is missing assembly version info, so packaged assembly has no version

### ISSUE THREAD

**Issue by aggieben** [haf/expecto#191]
This is the same problem as SuaveIO/suave#635.  PR incoming.

**Comment by seanamos** [comment]
Any chance we can see this released as a patch? Without an assembly version, binding redirects cannot be done.

**Comment by haf** [comment]
Ok, let's try to BUILD!!

Building...

**Comment by haf** [comment]
Released v5.0.1 – can you please test it?

**Comment by seanamos** [comment]
Thanks, will test shortly.

**Comment by haf** [comment]
Thank you

**Comment by seanamos** [comment]
Working!
