### ISSUE TITLE
Support async tests

### ISSUE THREAD

**Issue by haf** [haf/expecto#2]
Schedule all Job/Alt/Async/Task thingies and await their completions from e.g. `Expecto.Hopac`. This would probably require a 2-stage process with the first discovering the test and the second doing an execute-and-fan-in/join operation.

 1. Support non-monadic parallelism
 2. Support async/task/job etc
 3. Support limiting concurrency via configuration flag.

**Comment by haf** [comment]
Stub issue for #26

**Comment by AnthonyLloyd** [comment]
Willing to help. Do you have more idea of how you want this to work in terms of API.

**Comment by haf** [comment]
The tests are run either by enumerating a parallel or a sequenced sequence, which comes down to the `map` function passed in to the anonymous functions that `evalTestList` returns.

I created a scaffolding for you to work in; and refactored a bit of the control flow to make it easier for you to implement the basic lock feature.

We'll have to further consider the plugin infrastructure for monads, especially if we're talking things that can interfere with each other.

Please see the output and individual commits of `git show f0e97c5..0c243c9`, and see what you can make of it.
