### ISSUE TITLE
NullReferenceException thrown during testFromAssembly

### ISSUE THREAD

**Issue by Alxandr** [haf/expecto#202]
I'm getting a nullref exception during `testFromAssembly`. Full stacktrace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
   at Expecto.Impl.getTestFromMemberInfo@1138-1.Invoke(a focusedState)
   at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpOption`1 option)
   at Expecto.Impl.testFromMember(MemberInfo mi)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@165.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Expecto.Impl.testFromType@1167.Invoke(Type t)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@165.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Expecto.Impl.testFromAssemblyWithFilter(FSharpFunc`2 typeFilter, Assembly a)
   at YoloDev.Expecto.TestSdk.Discovery.discoverTests@143.GenerateNext(IEnumerable`1& next) in /Users/alxandr/hub/YoloDev.Expecto.TestSdk/src/YoloDev.Expecto.TestSdk/adapter.fs:line 149
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at YoloDev.Expecto.TestSdk.VsTestAdapter.Microsoft-VisualStudio-TestPlatform-ObjectModel-Adapter-ITestDiscoverer-DiscoverTests(IEnumerable`1 sources, IDiscoveryContext discoveryContext, IMessageLogger logger, ITestCaseDiscoverySink discoverySink) in /Users/alxandr/hub/YoloDev.Expecto.TestSdk/src/YoloDev.Expecto.TestSdk/adapter.fs:line 200
```

Running on dotnet core 2.0 on OSX

**Comment by AnthonyLloyd** [comment]
Thanks. I'll take a look later today.

Are you able to pin down anything different about the tests that cause this?

**Comment by Alxandr** [comment]
This is literally the entire thing (should probably have included in the original post):

```fsharp
module Test

open Expecto

[<Tests>]
let tests = 
  testList "list1" [
    testCase "test1" (fun () -> ()) ]
```

I'm loading the assembly using `Assembly.LoadFile`, and then passing it to `Expecto.Impl.testFromAssembly`. I'm trying to create a `dotnet test` adapter for expecto.

**Comment by AnthonyLloyd** [comment]
Thanks. Still looking at this...

**Comment by AnthonyLloyd** [comment]
I can't seem to reproduce. I've created 2 projects and I'm doing `Assembly.LoadFile` and `Expecto.Impl.testFromAssembly`.

I'm using the current Expecto codebase. Are you using the latest release?

**Comment by Alxandr** [comment]
not a minimal repo (will look at that later today), but this is the code that is failing (on my computer at least): https://github.com/YoloDev/YoloDev.Expecto.TestSdk

If you can run `dotnet test -t` in the `sample` dir without getting the same error, it might be a .NET problem on mac or somesuch.

**Comment by AnthonyLloyd** [comment]
Thanks. I can reproduce with your code.

`GetValue` on the `PropertyInfo` is returning null. I've tried a few different ways of getting the value it but always comes back null.

I've also tried `System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(m.DeclaringType.TypeHandle)` to make sure the static constructor has been called. It makes no difference.

Still working on it...

**Comment by Alxandr** [comment]
Which project needs to be changed? The `Sample` one, or the test runner? ALso, what makes it compile as an app? Cause I have to target `netcoreapp` unfortunately, and I think it would be bad requiring all test assemblies to be written with an entry point....

Also; could you consider catching this and throwing a more descriptive error if this is something common? Just something as simple as replacing `unbox` with a inline function that matches against `null`, and throws a better error would probably help quite a bit?

**Comment by AnthonyLloyd** [comment]
I think the sample needs to be either a classlib (without an [<EntryPoint>]) or a netcoreapp with an [<EntryPoint>]. Can you test to see if I'm correct on this?

I'll add catch and log an error that the test is null (which shouldn't possibly be).

Apart from that I don't know how to initialize an app that has no [<EntryPoint>] as per the SO description. If we find that I could add it too.

**Comment by Alxandr** [comment]
Yeah. I think it has to be `netcoreapp` though, to get the required `runtime.json` file. The question is if I can get the F# compiler to emit a library. Probably set `<Target>Library</Target>` or something similar. I'll try it out later today if I have the time. I'll be traveling this weekend so if I can't get to it today, it might be a while.

**Comment by Alxandr** [comment]
Quick testing shows that adding a entrypoint to the `sample` project works. I can't figure out how to create a library while also targeting `netcoreapp2.0` (which I have to do). So yeah, that unfortunately means that any test assembly created by expecto will have to have a entry-point :-/.

Btw; when you catch the `null` values in `getTestFromMemberInfo`, could you throw a strongly typed, well known (public API) exception? That way I could catch it and explain what the error is, and how to fix it.

**Comment by AnthonyLloyd** [comment]
Will do.

If you work out how to initialize an app without putting an `[<EntryPoint>]` on let me know.

**Comment by AnthonyLloyd** [comment]
Just added this. Let me know how you get on. Chase if you need this released soon.

**Comment by Alxandr** [comment]
Btw; I have a (seemingly) working runner for vstest (the new one) available at https://github.com/YoloDev/YoloDev.Expecto.TestSdk. Let me know if this is something you're interested in adopting.

Also, if you're not, I'm using a bunch of "internal" (`Expect.Impl`) apis, and I don't see how I could not currently, so Expecto might need a bigger API surface if `Expecto.Impl` is not supposed to be used.

It's currently in a very early state. It does not support filters or any such. Need to figure out how that works first.

![image](https://user-images.githubusercontent.com/112334/31687932-ebed3894-b38a-11e7-9321-057cc6c4a28a.png)

**Comment by MNie** [comment]
@Alxandr maybe it would be possible to merge somehow Your solution with [existing vs adapter](https://github.com/adamchester/expecto-adapter)

Also I suppose it would be worth to add a reference in an [expecto template](https://github.com/MNie/Expecto.Template) to your adapter/package, so `dotnet test` would work out of the box(?)

CC: @AnthonyLloyd

**Comment by AnthonyLloyd** [comment]
@Alxandr Yes I think this would be great to add. Can you consider integrating as @MNie has suggested.

**Comment by Alxandr** [comment]
To some extent, yes, but I think it would prove to be a somewhat fruitless effort as netcore does not have appdomains, which the old adapter is built heavily around (as far as I could tell). I looked quite a bit at the old adapter, and was mostly confused by a good part of it.

Also, the interfaces to implement have changed I believe, even though they have the same names. That being said, some form of isolation is probably a good idea (which will probably be appdomains on the full .net framework, and loadcontexts on netcore). I just made a minimal viable product mostly for self use currently.

**Comment by MNie** [comment]
@Alxandr in a long time period it would be better to have only one adapter instead of two, where one have some functionalities and another one have some other functionalities. Maybe it would be easier to adapt some code from an "old" adapter to your adapter and then "merge" them?

I look a little bit at your code and I saw that a couple of methods were copy-pasted from an Expecto. So I don't see any disadvantages to provide them/some of them as an api for users if it would help them creating something around Expecto. What do you think @AnthonyLloyd ?

**Comment by AnthonyLloyd** [comment]
Yes definitely. A clear API to help extend people extend Expecto.

Please suggest what needs to go there. I'll take a look next week also as I've seen the need to do this when writing tests for Expecto.

**Comment by Alxandr** [comment]
I'd at least like to point out one thing. Allow logging to be set in the config. Currently, it's sort of pseudo ephemeral magic, based on global state, which I find horrifying. Or I'm just not understanding it at all. If you want to use magic logging, that's fine, just make a default "logger" that forwards to the magic global state one. I need to be able to provide loggers per test suite being run.

**Comment by MNie** [comment]
@Alxandr @AnthonyLloyd so maybe it would be worth to create another issue where we could specify what should be available and why? So any contributor/user could comment it more easily instead of reading here a bunch of comments rather not related to an API?

**Comment by Alxandr** [comment]
Yep. I was thinking the same ^^

**Comment by AnthonyLloyd** [comment]
Closing and opening a new issue for this. Thanks
