### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Rajivhost** [haf/expecto#203]
Hi,
I got this when I try to install Expecto.FsCheck on my project.

![image](https://user-images.githubusercontent.com/3539984/31328563-ce39fbd4-accd-11e7-9fb0-0622c333ada8.png)

**Comment by MNie** [comment]
@rajivhost Did You try "Install-Package expecto.fscheck -pre"?

**Comment by Rajivhost** [comment]
I got this with "-pre"

![image](https://user-images.githubusercontent.com/3539984/31340802-3b2688b2-acff-11e7-9e84-a84702dcead8.png)

**Comment by Rajivhost** [comment]
Fixed using #188 issue.

**Comment by AnthonyLloyd** [comment]
Great, well done.
