### ISSUE TITLE
Exceptions lose their stack trace

### ISSUE THREAD

**Issue by haf** [haf/expecto#205]
E.g.

```
[15:09:44 ERR] aggregates/expenses/vouchers/within EU, reclaim VAT 2 failed in 00:00:00.2340000.
Input string was not in a correct format.


```

Now, where do I start to look?

**Comment by AnthonyLloyd** [comment]
What kinds of tests are these? Do you have an example.

I'll be looking a few things including this later today/tomorrow.

**Comment by AnthonyLloyd** [comment]
This is using a `FailedException` which as far as I can see is only used in FsCheck and isFasterThan tests.

I can't quite see how either of these could have generated that message.

Do you have details of the type of test and Expect called.

**Comment by haf** [comment]
Thanks for pointing me here. It was an actual issue, but I'm closing it for now due to lack of time to debug it. I'll come back when it inevitably comes up again.

**Comment by AnthonyLloyd** [comment]
Ok cool. I'll release this week. There is an issue on Arb.register that I'm waiting on but I don't think there is anything to do.

**Comment by haf** [comment]
Happens for `testCaseAsync`, when using `failtestf` failures.

**Comment by AnthonyLloyd** [comment]
Thanks will take a closer look.
