### ISSUE TITLE
sequenceEqual "char"

### ISSUE THREAD

**Issue by haf** [haf/expecto#206]
It's more like "item" in a sequence of arbitrary items, than a "char" in a sequence. The `equal` method does chars/strings.

**Comment by AnthonyLloyd** [comment]
Great. I'm looking to do a release soon. There are a couple of issues waiting for an answer (one from you!).

**Comment by haf** [comment]
I've unsubscribed from github messages, can you point me in the right direction?

Also, sorry for the force-push, but there was only ever history for a few minutes publicly available.

**Comment by AnthonyLloyd** [comment]
@haf #205 I can't seem to see how you could get that error.
