### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by haf** [haf/expecto#208]
...doesn't disappear "Anthony Lloyd (formerly Henrik Feldt and cloned from Fuchu by @mausch)". You're thinking of "owners" or "maintainers" or such.

**Comment by AnthonyLloyd** [comment]
Thanks. Should it just be a year like FsCheck (https://www.nuget.org/packages/FsCheck/3.0.0-alpha2)?

**Comment by haf** [comment]
Yes.

**Comment by haf** [comment]
What's your NuGet username? I realised I haven't given you rights to the nuget

**Comment by AnthonyLloyd** [comment]
AnthonyLloyd Thanks

I've been thinking about moving the repo further. I think it would be best to put it to an org. I'm thinking about making the readme into a docs site and think the adapters could be moved there too. There have been discussing of sharing the adapter logic.

I've created ExpectoIO for this. You can move it to there but there's no rush.

**Comment by haf** [comment]
I'm not convinced of moving this to a new organisation for this repo just yet, like I said on twitter. Are you thinking of the reflection logic required for tooling?

**Comment by AnthonyLloyd** [comment]
Just that the adapter writers wanted to pull out shared code and not have it in each others repos.

Don't do anything for now and we can see in the future.
