### ISSUE TITLE
Release Expecto.BenchmarkDotnet .NETCoreApp 1.1 and .NETCoreApp 2.0

### ISSUE THREAD

**Issue by TheAngryByrd** [haf/expecto#214]
Is it possible to release [Expecto.BenchmarkDotnet](https://www.nuget.org/packages/Expecto.BenchmarkDotNet/) for .NETCoreApp 1.1 and .NETCoreApp 2.0?

**Comment by AnthonyLloyd** [comment]
I had real trouble doing this in the previous release. I'll take another look in the next few days now things settled.

**Comment by TheAngryByrd** [comment]
I was curious if it was just an oversight or dotnet tooling being painful.  Let me know if there’s anything I can do to help

**Comment by AnthonyLloyd** [comment]
Released this now.

**Comment by TheAngryByrd** [comment]
Circling back to this, are the docs correct for this? https://github.com/haf/expecto#benchmarkdotnet-usage
testList needs to take a `Test` but benchmark doesn't return one.

**Comment by AnthonyLloyd** [comment]
Yes the docs are out of date. It need to be put in a test:

https://github.com/haf/expecto/blob/master/Expecto.BenchmarkDotNet/Expecto.BenchmarkDotNet.fs#L8

I'll update, thanks

**Comment by AnthonyLloyd** [comment]
This is corrected now.
