### ISSUE TITLE
exception crashes tests

### ISSUE THREAD

**Issue by forki** [haf/expecto#22]
I have a exception in my test project (see https://github.com/fsprojects/Canopy.Mobile/blob/master/tests/Canopy.Mobile.Tests/Tests.fs#L51)

and this crashes the whole test project.

![image](https://cloud.githubusercontent.com/assets/57396/21294089/d876cdd2-c535-11e6-91c8-c13e214c9fb1.png)

![image](https://cloud.githubusercontent.com/assets/57396/21294086/a5031992-c535-11e6-9cfb-ca70bb1fb76c.png)

FAKE can't recover from that. What's the proper way to work around that?

**Comment by haf** [comment]
I'm not sure why it would crash the process. Each test is run like [this](https://github.com/haf/expecto/blob/master/Expecto/Expecto.fs#L434-L441) and obviously I've had tests throwing exceptions myself. Do you have a stack trace? Can you break on exception in VS and create a dump? Could you write a unit test?

**Comment by forki** [comment]
I think it crashes in the entry point code. Stack trace is in the screen
shot

Am 18.12.2016 17:16 schrieb "Henrik Feldt" <notifications@github.com>:

**Comment by haf** [comment]
Well, if it crashes outside of expecto there's nothing this library can do.

**Comment by forki** [comment]
Yes I do understand that: I was wondering what the best way is to do startup and teardown stuff.

**Comment by haf** [comment]
```fsharp
let main argv =
  try
    Canopy.Mobile.tests.start ()
    Tests.runTestsInAssembly defaultConfig args
  with e ->
    -1
  finally
    ()
```
?

**Comment by forki** [comment]
ok. thought you might have different plans for that. so that reporting and stuff works ;-)

**Comment by haf** [comment]
For me, exceptions are always an edge-case; if you program with them, you'll ultimately end up sinking a lot of time into working around them... ;)

**Comment by forki** [comment]
that stuff is coming from the selenium/appium layer. It's not like I want them to throw.

**Comment by haf** [comment]
I know. :)

**Comment by forki** [comment]
Also I wonder if test lists could contain setup and teardown code?

Am 18.12.2016 17:57 schrieb "Henrik Feldt" <notifications@github.com>:

**Comment by haf** [comment]
It's possible. You could do some sketches of it and we can discuss. Another way is to use hole-in-the-middle factory functions like we do in the suave tests.

**Comment by forki** [comment]
Holes sounds awesome. Go for it ;-)

Am 18.12.2016 18:33 schrieb "Henrik Feldt" <notifications@github.com>:

It's possible. You could do some sketches of it and we can discuss. Another
way is to use hole-in-the-middle factory functions like we do in the suave
tests.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/haf/expecto/issues/22#issuecomment-267834479>, or mute
the thread
