### ISSUE TITLE
Request: config option to pick name for logging (not hardcoded to "Expecto")

### ISSUE THREAD

**Issue by rmunn** [haf/expecto#223]
Currently when [Expecto sets up logging](https://github.com/haf/expecto/blob/dd476c4066b0e472a682598af72fd7f2d4ad6e86/Expecto/Expecto.fs#L415), it uses the name "Expecto" (hardcoded) for the logger name, so that any log output from Expecto has `<Expecto>` printed at the end. If you run several instances of Expecto at once, it can become unclear which log message comes from which instance.

The use case that leads me to ask for this is https://github.com/TheAngryByrd/MiniScaffold/, which runs Expecto tests under three different frameworks (currently `net461`, `netcoreapp1.1`, and `netcoreapp2.0`) by default. It runs all three tests in parallel, which can sometimes result in output like the following:

```plaintext
[10:29:27 INF] EXPECTO? Running tests... <Expecto>
[10:29:28 INF] EXPECTO! 1 tests run in 00:00:00.0955849 – 1 passed, 0 ignored, 0 failed, 0 errored. ᕙ໒( ˵ ಠ ╭͜ʖ╮ ಠೃ ˵ )७ᕗ <Expecto>
watch : Exited
watch : Waiting for a file to change before restarting dotnet...
[10:29:28 INF] EXPECTO? Running tests... <Expecto>
[10:29:28 INF] EXPECTO? Running tests... <Expecto>
[10:29:28 INF] EXPECTO! 1 tests run in 00:00:00.1374021 – 1 passed, 0 ignored, 0 failed, 0 errored. ᕙ໒( ˵ ಠ ╭͜ʖ╮ ಠೃ ˵ )७ᕗ <Expecto>
[10:29:28 INF] EXPECTO! 1 tests run in 00:00:00.0931585 – 1 passed, 0 ignored, 0 failed, 0 errored. ᕙ໒( ˵ ಠ ╭͜ʖ╮ ಠೃ ˵ )७ᕗ <Expecto>
watch : Exited
watch : Waiting for a file to change before restarting dotnet...
watch : Exited
watch : Waiting for a file to change before restarting dotnet...
```

If one of the frameworks had had a test failure while the other two passed, it would be hard for me to tell which test had failed. Was it the `netcoreapp1.1` framework? The `net461` framework? I don't know.

Therefore, I'd like to be able to specify in some way (a command-line flag would be ideal for my use case) what name the Expecto logger should use, rather than hardcoding it to "Expecto". If I could have had log messages like `<Expecto.net461>` and `<Expecto.netcoreapp2.0>`, it would be easy to tell which of the three simultaneous runs had caused the error.

I could probably achieve this by configuring the Logary facade in some way, but that feels like overkill for this particular scenario. I don't really want to change the log targets or the formatting, I just want to be able to pick the name that Expecto uses in the line `let logger = Log.create "Expecto"` so that I can differentiate between different processes that are logging simultaneously.

Is this something that would be simple to achieve, or would it require far more work than I think it would?

**Comment by AnthonyLloyd** [comment]
Yes this looks to be a reasonably easy change to put in a command-line flag and hook it up to the `Log.create`. The only issue I see is adding command line flags at the moment has to be coordinated with the `Expecto` test adapter projects.

If you go ahead and submit a PR I will coordinate this. Alternatively I can do do this next week sometime (currently working on a blog).

**Comment by rmunn** [comment]
I'll take a shot at this. The one thing that might be tricky is that `Impl.logger` is referenced by some static methods, so it's a little tricky to pass it around as a value. I might punt on trying to do it in a "purely functional" way, and just make `logger` a mutable variable of the `Impl` module, and then if a `--log-name Foo` argument gets passed on the command line, replace the `logger` variable with a new logger named "Foo". As long as that happens right at the start of `runTests`, I think it should work. (This seems to be [the approach taken by Logary](https://github.com/logary/logary/blob/1ef55a8666f188d54998e972290c4940e7e43871/src/Logary.Facade/Facade.fs#L878) as well, so I don't feel too bad about "cheating" like this.)

**Comment by AnthonyLloyd** [comment]
I think that's fine for now. Please go ahead.

**Comment by rmunn** [comment]
If you can think of a better parameter help text, or a better name than `--log-name`, please go ahead and change it. That's just the best name that occurred to me in five minutes of thinking, and I'm not attached to it or anything. (I usually prefer to get feedback from others on things like command-line parameters, and I couldn't this time). It's a *pretty* good name, but it's not necessarily the *best* name.

**Comment by AnthonyLloyd** [comment]
Release in 6.0.0. Thanks
