### ISSUE TITLE
Expecto.BenchmarkDotNet TypeLoadException get_ArtifactsPath

### ISSUE THREAD

**Issue by TheAngryByrd** [haf/expecto#225]
Taking the https://github.com/haf/expecto#benchmarkdotnet-usage example I'm running into an exception:

`dotnet run -f netcoreapp2.0 -c Release`

```
performance tests/three serialisers errored in 00:00:00.0190000 <Expecto>
System.TypeLoadException: Method 'get_ArtifactsPath' in type 'BenchmarkConfig' from assembly 'Expecto.BenchmarkDotNet, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Tests.tests@55-1.Invoke(Unit unitVar)
   at Expecto.Impl.execTestAsync@878-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
```

**Comment by AnthonyLloyd** [comment]
Hmm. I was running into strange errors with benchmarkdotnet and it was the main reason I split it out as a dependency. I'll have to set this up as a test and see what I can do.

**Comment by AnthonyLloyd** [comment]
I've added a test project for this. It's currently working for net461 & netcoreapp2.0 but not netcoreapp1.1. Also plenty of warnings about Microsoft.NETCore.App.

Will continue.
