### ISSUE TITLE
Could not load file or assembly 'FSharp.Core, Version=4.4.3.0

### ISSUE THREAD

**Issue by halcwb** [haf/expecto#228]
I used the below steps to setup my project:

1. Use `dotnet new sln -n GenFormService` to create the solution file. This will create a solution file with the name `GenFormService.sln`.
2. Add a new project using `dotnet new classlib -lang F# -o src/Informedica.GenUtils.Lib -n Informedica.GenUtils.Lib`. This will add a project in the `src/Informedica.GenUtils.Lib` folder with the project file: `Informedica.GenUtils.Lib.fsproj`.
3. Add the project to the sln file: `dotnet sln add src/Informedica.GenUtils.Lib/Informedica.GenUtils.Lib.fsproj`. The project is now part of the solution.
4. Go to the project folder and add a package reference to the project using `dotnet add package MathNet.Numerics.FSharp --version 4.4.0`. This will add for example the MathNet.Numerics.FSharp package as a reference. Check for each package if there is a dotnet version available, otherwise you're in trouble.
5. Open the solution folder using *Visual Studion Code* to create a `fsx` file with references for the FSI. Look with `SHFT-CMD-P` for `>FSI: Generate script file with references from project`. You need to open a source file for this command to popup up. You can then with `Save As..` save the file in the appropriate folder. This file can then be used in the FSI to load all required references.
6. **DO NOT USE** *Visual Studio* to add the folder with the `references.fsx` file to the project. This will mess up your project file by adding the `fsx` file as a `<Compile Include="scripts\references.fsx" />` instead of a `<None Include="scripts\references.fsx" />`. So a `None` include instead of a `Compile` include.
7. To add an existing source file, copy the file to your project folder and add the file in the `fsproj` manually to be on the save side.
8. Add the Expecto test template: `dotnet new -i "Expecto.Template::*"`.
9. Add a test project by `dotnet new expecto -o tests/Informedica.GenUtils.Tests -lang F# -n Informedica.GenUtils.Tests`. Add this test project to the solution by `dotnet sln add tests/Informedica.GenUtils.Tests/Informedica.GenUtils.Tests.fsproj`. And add a project reference to the expecto test project: `dotnet add tests/Informedica.GenUtils.Tests/Informedica.GenUtils.Tests.fsproj reference src/Informedica.GenUtils.Lib/Informedica.GenUtils.Lib.fsproj`.

With this setup when I run: `dotnet run -p tests/Informedica.GenUtils.Tests/Informedica.GenUtils.Tests.fsproj ` I get:

> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I tried the redirects as described on: https://fsharp.github.io/2015/04/18/fsharp-core-notes.html. However with no results.

**Comment by halcwb** [comment]
When I try the setup using paket I avoid the FSharp.Core version issue, but I get a:

> Unhandled Exception: System.MissingMethodException: Method not found: 'Void Argu.ArgumentParser`1..ctor(Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<Int32>, Microsoft.FSharp.Core.FSharpOption`1<Argu.IExiter>)'.
>    at Expecto.Tests.ExpectoConfigModule.fillFromArgs(ExpectoConfig baseConfig, String[] args)
>    at Expecto.Tests.runTestsWithArgs(ExpectoConfig config, String[] args, Test tests)
>

**Comment by haf** [comment]
@halcwb Just ref `~> 4` of argu.

**Comment by halcwb** [comment]
Did that (although isn't this a transitive dependency resolved by paket?). Added it to the paket.dependencies and to the test project paket.references files. Cleaned the project. But still getting the error message.

**Comment by haf** [comment]
Ok, = 3.7 then, that's what the ref of expecto is at. See #227

**Comment by halcwb** [comment]
Sorry, I forget to restrict Argu to ~> 4. Adding that to the paket.dependencies file solved the issue. Thanks a lot!! I was getting quit frustrated after almost a week of trial and error.

**Comment by haf** [comment]
I think your repro shows a real issue for users like yourself, so I'd like to keep this issue open until we have an answer from one of the powers that be; on how to version F# libraries' usage of F# Core.

**Comment by AnthonyLloyd** [comment]
Released upgrade of Argu to 5.1 in Expecto v7.0.0. Please let me know how works for you. Will close this soonish.
