### ISSUE TITLE
runTests returns 0 when a test fails

### ISSUE THREAD

**Issue by isaacabraham** [haf/expecto#23]
Just tried my first expecto hello world: -

```fsharp
module Tests

open Expecto

[<Tests>]
let tests =
    testCase "hello world" <| fun _ ->
        Expect.equal 1 2 "Should be equal"


[<EntryPoint>]
let main args =
    runTests defaultConfig tests
```

However, whilst the output shows a test failure, the program returns 0 when (AFAIK) it should return 1 because of the test failure.

**Comment by haf** [comment]
Fixed with #29, closing.
