### ISSUE TITLE
Keep running into version problems

### ISSUE THREAD

**Issue by halcwb** [haf/expecto#232]
I added a new test project to my solution then I got:

> /Users/hal/Development/GenFormService/tests/Informedica.GenUnits.Tests/Informedica.GenUnits.Tests.fsproj : warning NU1605: Detected package downgrade: Expecto from 7.0.0 to 5.1.2. Reference the package directly from the project to select a different version.  [/Users/hal/Development/GenFormService/GenFormService.sln]
> /Users/hal/Development/GenFormService/tests/Informedica.GenUnits.Tests/Informedica.GenUnits.Tests.fsproj : warning NU1605:  Informedica.GenUnits.Tests -> Expecto.FsCheck 7.0.0 -> Expecto (>= 7.0.0)  [/Users/hal/Development/GenFormService/GenFormService.sln]
> /Users/hal/Development/GenFormService/tests/Informedica.GenUnits.Tests/Informedica.GenUnits.Tests.fsproj : warning NU1605:  Informedica.GenUnits.Tests -> Expecto (>= 5.0.0) [/Users/hal/Development/GenFormService/GenFormService.sln]
> /Users/hal/Development/GenFormService/tests/Informedica.GenUnits.Tests/Informedica.GenUnits.Tests.fsproj : warning NU1605: Detected package downgrade: Expecto from 7.0.0 to 5.1.2. Reference the package directly from the project to select a different version. 
> /Users/hal/Development/GenFormService/tests/Informedica.GenUnits.Tests/Informedica.GenUnits.Tests.fsproj : warning NU1605:  Informedica.GenUnits.Tests -> Expecto.FsCheck 7.0.0 -> Expecto (>= 7.0.0) 
> /Users/hal/Development/GenFormService/tests/Informedica.GenUnits.Tests/Informedica.GenUnits.Tests.fsproj : warning NU1605:  Informedica.GenUnits.Tests -> Expecto (>= 5.0.0)
>     2 Warning(s)
>     0 Error(s)

Cleaning the whole solution, deleting and reinstalling using paket nothing seems to help?? This is weird as I don't understand why there is a downgrade of expecto?

This is the relevant paket.lock file part:

```
GENERATE-LOAD-SCRIPTS: ON
REDIRECTS: FORCE
STORAGE: NONE
RESTRICTION: || (== netcoreapp2.0) (== netstandard2.0)
NUGET
  remote: https://api.nuget.org/v3/index.json
    Argu (5.1)
      FSharp.Core (>= 4.3.2)
      System.Configuration.ConfigurationManager (>= 4.4)
    Expecto (7.0)
      Argu (>= 5.1)
      Mono.Cecil (>= 0.10.0-beta7)
      System.Diagnostics.FileVersionInfo (>= 4.3)
    Expecto.FsCheck (7.0)
      Expecto (>= 7.0)
      FsCheck (>= 2.10.4)
    FsCheck (2.10.8)
      FSharp.Core (>= 4.2.3)
      NETStandard.Library (>= 1.6.1)
      System.ValueTuple (>= 4.4)
    FSharp.Core (4.3.4)
    MathNet.Numerics (4.4)
    MathNet.Numerics.FSharp (4.4)
      FSharp.Core (>= 4.3.3)
      MathNet.Numerics (>= 4.4)
    Microsoft.NETCore.Platforms (2.0.1)
    Microsoft.NETCore.Targets (2.0)
    Mono.Cecil (0.10.0-beta7)
```

**Comment by halcwb** [comment]
Ok, I got it, I use `dotnet new expecto` to install the test project. Only this refers to an old expecto version that conflicts with the current version installed by paket.

**Comment by AnthonyLloyd** [comment]
Cool. So there's no error and I can close? Else reopen, thanks.

**Comment by haf** [comment]
Is this with @MNie 's template?

**Comment by AnthonyLloyd** [comment]
@Mnie is looking to update these later today I think.

**Comment by MNie** [comment]
@halcwb [Template relased](https://github.com/MNie/Expecto.Template/releases/tag/8.0.0) sorry for inconvenience!

**Comment by halcwb** [comment]
No problems, thanks for the quick response!
