### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by jackfoxy** [haf/expecto#237]
Would you accept a PR to add paket-files to .gitignore?

Running the build script updates paket-files/logary/logary/src/Logary.Facade/Facade.fs, which clutters the git status.

**Comment by haf** [comment]
Yes

**Comment by AnthonyLloyd** [comment]
I've had someone else ask why it gets added.

I'd like it that this wasn't the case and also you can build/explore the projects straight from cloning. I think that means we need to pin this file in paket.

**Comment by jackfoxy** [comment]
@AnthonyLloyd  I just cloned master to a new folder and built with the build script, no problem.

**Comment by AnthonyLloyd** [comment]
I mean dotnet build without running the build script. So you can just clone and explore the code.

**Comment by jackfoxy** [comment]
You  might want someone who does this as part of their regular workflow test that. I'm still old school when it comes to builds.

**Comment by AnthonyLloyd** [comment]
Thanks. I think its a whitespace issue. It's the same with AssemblyInfo. I've still never found the perfect git settings for this.

**Comment by jackfoxy** [comment]
My experience was the build script made substantive changes to this file. It was not just line endings. I'm pretty sure this change will also work for dotnet commands.

**Comment by AnthonyLloyd** [comment]
I've fixed up the line ending changes on build so it results in no changes now.
