### ISSUE TITLE
C# example find no tests in assembly

### ISSUE THREAD

**Issue by vilinski** [haf/expecto#241]
Didn't tried expecto with C# before. Surely I do something wrong.

I have created a project with `dotnet new console` and added the C# example [Tests.cs](https://github.com/haf/expecto/blob/master/Expecto.Tests.CSharp/Tests.cs). 
But it doesn't prints anything out by `dotnet run` and lists no tests by `botnet run --list-tests`.

this is my solution for reproduction.
[expectocs.zip](https://github.com/haf/expecto/files/1905041/expectocs.zip)

>Expecto (7.0.1)

dotnet --version
> 2.1.104

mono --version
> Mono JIT compiler version 5.10.0.160 (2017-12/f3ac8fdeb37 Tue Mar  6 14:07:30 EST 2018)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
> 	TLS:           normal
> 	SIGSEGV:       altstack
> 	Notification:  kqueue
> 	Architecture:  amd64
> 	Disabled:      none
> 	Misc:          softdebug
> 	Interpreter:   yes
> 	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
> 	GC:            sgen (concurrent by default)

**Comment by FoggyFinder** [comment]
I guess it's searching only in public classes, so you have to change the line:

```csharp
class Program
```

to

```csharp
public class Program
```

**Comment by vilinski** [comment]
Yes, thanks!
Turns out both the class and the test field should be public. 
Visual Studio normally creates `class Program`...
Sorry for the noise. :)
