### ISSUE TITLE
Relative statistical performance testing 

### ISSUE THREAD

**Issue by AnthonyLloyd** [haf/expecto#26]
I'm up for putting together a PR to add a function `isFasterThan f1 f2` along the lines of my perf blog [post](http://anthonylloyd.github.io/blog/2016/05/20/performance-testing).

One issue I can see is it would be best if these test cases run sequentially but should not stop the others from running in parallel. Maybe these could be run at the end of the run.

I also don't know if therefore the function should be on `Expect` or should be a new type of Test.

Let me know if this would be a good fit for the library and any help on the API.

**Comment by haf** [comment]
I envision that it's possible to tag test cases; different runner concerns can then inspect these tags and choose how to execute.

In this case, we'd like to tag a test case with 'performance' which would have a concern in the main library that serialises running of such test cases.

This should go towards a runner that can also support `Job<'a>` and `Async<'a>` in the future.

If the running of the test case is enforced to be sequential, then there's nothing stopping `Expect` to report the (success)/failure.

**Comment by AnthonyLloyd** [comment]
I'll do the PR in the next week or so to put it in best I can see at the moment.

Feel free to change it around as best suits.

**Comment by AnthonyLloyd** [comment]
Sorry a bit of a false start. I'm trying to build and run existing tests from VS or command line on windows. Both give me the following. What am I doing wrong?

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
 The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Expecto.Tests.ExpectoConfigModule.fillFromArgs(ExpectoConfig baseConfig)
   at Expecto.Tests.runTestsInAssembly(ExpectoConfig config, String[] args) in C:\Users\Ant\src\expecto\Expecto\Expecto.fs:line 775
   at Main.main(String[] args) in C:\Users\Ant\src\expecto\Expecto.Tests\Main.fs:line 7

**Comment by haf** [comment]
My guess would be that you need a F# core redirect.

**Comment by Krzysztof-Cieslak** [comment]
Can confirm that on Windows I also need binding redirects to run `Expecto.Tests`

**Comment by haf** [comment]
We should add redirects to the repo then.

**Comment by Krzysztof-Cieslak** [comment]
I;m pretty sure we can make Paket to generate them automatically... but only @forki knows how ;)

**Comment by AnthonyLloyd** [comment]
Yes that did it. Thanks. Will include in the PR if you want it that way.

**Comment by AnthonyLloyd** [comment]
#34

**Comment by AnthonyLloyd** [comment]
Happy to look at other extensions of this at a later date.
