### ISSUE TITLE
Test.run returns 1 when all enabled tests pass, but pending tests present

### ISSUE THREAD

**Issue by jackfoxy** [haf/expecto#264]
Would you consider a different return integer for the use case of all enabled tests passing, but some tests ignored (marked pending)?

**Comment by AnthonyLloyd** [comment]
As far as  can see it only returns 1 if 1) a test fails 2) fail on focus or 3) duplicate test names? Do you see this with pending?

https://github.com/haf/expecto/blob/b81d5be1eeb1f7d02b03ebd4b8ee24ea58a17e12/Expecto/Expecto.fs#L1700

**Comment by jackfoxy** [comment]
My mistake. Investigated again and you are correct.
