### ISSUE TITLE
[Logging] v8.2 logging broken

### ISSUE THREAD

**Issue by haf** [haf/expecto#267]
<img width="1132" alt="screen shot 2018-07-25 at 21 26 14" src="https://user-images.githubusercontent.com/193115/43222789-6be22cb4-9051-11e8-8f1c-babacc6a0824.png">

<img width="536" alt="screen shot 2018-07-25 at 21 32 23" src="https://user-images.githubusercontent.com/193115/43223090-4b957f96-9052-11e8-9022-473a7bc176e9.png">

`--debug` has started failing: it doesn't print status as it goes.

The output is very strange; it keeps writing `Expecto running...`, overwriting previous text in part.

It doesn't show what test is being run either, which was why `--debug` was useful before.

Expected output (piece of it):

<img width="874" alt="screen shot 2018-07-25 at 21 42 48" src="https://user-images.githubusercontent.com/193115/43223538-b9a2c9f2-9053-11e8-9d82-38eff654a534.png">

**Comment by AnthonyLloyd** [comment]
I've not special cased --debug, will need to do that.

I'm not sure about the incorrect progress update. Will check the backspacing. What is this console? I may have to put a switch to turn off progress if we can't get it to work.

On a Scottish island this week. Will take a look on Monday.

**Comment by haf** [comment]
iTerm in zsh.

**Comment by AnthonyLloyd** [comment]
I've released v8.2.1 that auto flushes for --debug and also hopefully fixed the progress backspace issue.
Let me know how it looks. If we still have issues with the shell I may need to add a disable command line parameter.

**Comment by t1m0thyj** [comment]
v8.2.1 has broken logging for me, this happens in ConEmu:
![image](https://user-images.githubusercontent.com/22344007/43478428-dab2e90c-94cb-11e8-9803-c37088934fe6.png)

When I downgrade to v8.2.0 the problem goes away:
![image](https://user-images.githubusercontent.com/22344007/43478697-8fca9178-94cc-11e8-8b08-d109becf8b62.png)

**Comment by AnthonyLloyd** [comment]
@t1m0thyj How are creating the starting/finishing output messages?

**Comment by t1m0thyj** [comment]
Sorry for the delay, I've created a minimal repro [here](https://github.com/t1m0thyj/expecto-267).

The expected output can be seen in the `testWrapper` function:
```
let testWrapper (name, testFunc) () =
  printfn "Starting test (this is a very long message): %s" name
  testFunc ()
  printfn "Finished test: %s" name
```
But with Expecto 8.2.1, I get this output:
![image](https://user-images.githubusercontent.com/22344007/43841015-2468c66e-9af0-11e8-99c6-11101e7dc011.png)

**Comment by abk-x** [comment]
Hello, I am having the exact same issue, I have a library under test that uses logary to print debug messages to the console, and 8.2.1 seems to cause the same issues as @t1m0thyj. Reverting to 8.1.1 fixes it for me.

**Comment by AnthonyLloyd** [comment]
Thanks. I'll take a look over the next few days. If I can't reproduce and resolve I'll put in a command line switch. Would rather not have to do this.

**Comment by AnthonyLloyd** [comment]
@t1m0thyj thanks for the repo, it really helped.

The problem is each printfn can create multiple calls to stdout that aren't batched. In the last release I auto flush these.

I need to change the code to keep them until there is a newline. Release coming soon.

**Comment by ctaggart** [comment]
I'm hitting this again with 8.7, but not 8.6.

**Comment by AnthonyLloyd** [comment]
@ctaggart Thank I will take a look. Does the repo above show this or do you have a repo? There is a release coming up soon so I'll try to add it to that.

**Comment by ctaggart** [comment]
Happy to test a prerelease if there is one on Monday. Thanks for trying to reproduce.

**Comment by haf** [comment]
I've upgraded Logary to latest Expecto and it works for me.
