### ISSUE TITLE
--version doesn't seem to work

### ISSUE THREAD

**Issue by 0x53A** [haf/expecto#268]
This is the output I get when calling Expecto from Fake:

```
Starting target 'RunTests'
Starting task 'Expecto': Tests.exe
Tests.exe --parallel-workers 0 --fail-on-focused-tests --sequenced --version 
EXPECTO version 

[17:11:10 INF] EXPECTO? Running tests... <Expecto>

```

Note how it just prints ``EXPECTO version``

~Unrelated question:~

~what is the INF in ``[17:11:10 INF] EXPECTO? Running tests... <Expecto>``?~  
_(Apparently it stands for Informational, the log level. I thought at first it was some floating point issue (INFINITY) ;D)_

__Edit:__

```fsharp
    let expectoVersion() =
      let assembly = typeof<ExpectoConfig>.GetTypeInfo().Assembly
      let fileInfoVersion = FileVersionInfo.GetVersionInfo assembly.Location
      fileInfoVersion.ProductVersion
```

Executing the code in fsi, ProductVersion is empty.

__Edit2:__

Afaik FileInfoVersion gets its information from here:

![grafik](https://user-images.githubusercontent.com/4236651/43330081-6db16a60-91c2-11e8-8183-a3803eac8a1d.png)

Should the code be changed to instead read the assembly version?

__Edit3:__

If I do a local build, the information is correct:

![grafik](https://user-images.githubusercontent.com/4236651/43330291-0933cab4-91c3-11e8-8fc6-87848f9e23f7.png)

Could this be either a linux issue, or an issue with an older dotnet sdk? I have 2.1.301

**Comment by haf** [comment]
This is most likely a build issue; what nuget version are you using?

**Comment by 0x53A** [comment]
I checked [6.0 ; 8.1.1] and they all have an empty product version
