### ISSUE TITLE
For Task based tests, exceptions are printed twice

### ISSUE THREAD

**Issue by 0x53A** [haf/expecto#269]
![grafik](https://user-images.githubusercontent.com/4236651/43632498-a0066d3c-9706-11e8-8d11-62dd033e0718.png)

**Comment by adamchester** [comment]
Hi @0x53A, there is only one exception there (although it is an aggregate exception, so it contains one or more inner exceptions too), and the output is more or less what ToString() on the exception would generate.

Does this help?

**Comment by 0x53A** [comment]
Hi @adamchester, yes, the output is correct.

I didn't write it (I should have maybe elaborated a bit more instead of just posting a screenshot ;) ), but my intention was to propose to unwrap AggreagateExceptions.

This is really common and annoying with Task based tests from c#.

What do you think of https://github.com/haf/expecto/pull/270?

**Comment by adamchester** [comment]
My preference is not to hide the fact that it’s wrapped in an aggregate exception, but I can understand the argument for cleaning it up a little.

**Comment by AnthonyLloyd** [comment]
I think this does simply for single exceptions. Will accept.

**Comment by 0x53A** [comment]
@adamchester for reference, the above screenshot was from this source code:

```c#
                Runner.FocusedTestCase("focused async", async () => {
                    throw new IOException("Hello World!");
                }),
```

**Comment by adamchester** [comment]
:+1:
