### ISSUE TITLE
Logging in 8.2.2 prints ANSI to non-ANSI consoles

### ISSUE THREAD

**Issue by haf** [haf/expecto#271]
## Problem:

<img width="1666" alt="screen shot 2018-08-18 at 21 09 40" src="https://user-images.githubusercontent.com/193115/44302566-98f64e00-a32b-11e8-87e3-1c72c087fa6d.png">

## Solution:

<img width="1654" alt="screen shot 2018-08-18 at 21 13 29" src="https://user-images.githubusercontent.com/193115/44302567-9f84c580-a32b-11e8-9c2e-8533642b22c5.png">

Real solution? Allow configuration option that replaces the literate console logger? Or alternatively someone check whether the console supports that type of output.

**Comment by AnthonyLloyd** [comment]
Yes. I was hoping it wouldn't be needed. But that hope has died. Will add a config option.

**Comment by AnthonyLloyd** [comment]
switch no-spinner added. Will need a bit of a coordinated release next time for dependent projects.

**Comment by haf** [comment]
Also, it would seem that the console output (albeit not necessarily F# interactive) in Rider supports the new colourisation code of yours!
