### ISSUE TITLE
Is it possible to extend Expecto command-line options with custom ones?

### ISSUE THREAD

**Issue by object** [haf/expecto#273]
We need to send additional command-line options to an application running Expecto tests. One way is to strip custom options out of argv array and only send to a test runner the ones that Expecto expects. But is there a way to have an extended option collection, so custom options will coexist with standard ones?

**Comment by haf** [comment]
This depends on what Argu supports, really. I disable throw on unknown in Argu, and strip out the program's arguments before passing it to expecto's parser, myself.

**Comment by object** [comment]
This is what we are doing now before passing arguments to expecto. Thanks for the clarification.
