### ISSUE TITLE
Expect.equal on records

### ISSUE THREAD

**Issue by davidtme** [haf/expecto#276]
I use the Expect.equal to test if records are the same but on records with quite a few fields the message from equal isn’t always helpful as it can be quite long and difficult to see where the mismatch is.

Could the message be altered to include a bit of help? Maybe just passing the 2 records through a sprintf “%A” and using the same logic as this diffString could be a big help.

**Comment by MNie** [comment]
@davidtme @haf 
Does it look good for you guys?
![image](https://user-images.githubusercontent.com/7689103/45718287-cd646080-bb9c-11e8-9325-0265c060dae0.png)
