### ISSUE TITLE
"focused" feature should be ignored in CI

### ISSUE THREAD

**Issue by forki** [haf/expecto#28]
Do we already have a cmd line switch for that so that FAKE runner can set it? /cc @vilinski

**Comment by vilinski** [comment]
is it a good idea to add CustomArg for new arguments? https://github.com/fsharp/FAKE/pull/1439

**Comment by forki** [comment]
Yes we definitely need customargs

Am 22.12.2016 5:58 nachm. schrieb "Andreas Vilinski" <
notifications@github.com>:
