### ISSUE TITLE
ftestPropertyWithConfig signature does not match testPropertyWithConfig

### ISSUE THREAD

**Issue by Karamell** [haf/expecto#281]
`ftestPropertyWithConfig`has a different signature than `testPropertyWithConfig` and `ptestPropertyWithConfig. Wit would be nice if they were the same.

**Comment by AnthonyLloyd** [comment]
Yes the f signature takes a failing stdgen. I think we need another one when you don't want to specify that.
Will be a breaking change but not a bad one. I'd say 'f' for just focus and 'e' for focus on error.

Easy enough and will plan for the next release which are coming in about every 3-4 weeks.

**Comment by Karamell** [comment]
I'd like that. Thank you. 👍
