### ISSUE TITLE
Convert config to a DU

### ISSUE THREAD

**Issue by AnthonyLloyd** [haf/expecto#283]
This is to ensure strict binary compatibility for the API going forward.

- [x] Replace the config record with a DU.
- [x] Remove Argu dependency.
- [ ] Reconsider any other public APIs for removal.

**Comment by haf** [comment]
Why are we removing the Argu dependency? Seems like it works really well.

**Comment by AnthonyLloyd** [comment]
1. We've had dependency problems in the past where we git away with just upgrading it but possible needed to ilmerge it. Would be good to get to no dependencies (not too far off).
2. The maintainer has said they have little need/interest in it going forward.
3. I'm not a fan of reflection based solutions and have some ideas how it can be done differently.

**Comment by haf** [comment]
1. Upgrading the dependency is a pretty good workaround IMO; it's cheap and everyone understands it. This is similar to e.g. how the Node community works around similar issues.
 2. True, but it's also working and in use and we have the ability to push new versions of it, should it be needed. It's not holding us back, is what I'm saying. Stable, working code, in other words.
 3. Cool, let's just not throw out the baby with the bath water. ;)

**Comment by AnthonyLloyd** [comment]
Sure. If my experiment isn't enough of an improvement then it's not worth the risk.

**Comment by AnthonyLloyd** [comment]
Done in v8.9.0

**Comment by auduchinok** [comment]
I'm a bit late to the party but I want to say thank you so much for doing this!
