### ISSUE TITLE
Q: A grey world

### ISSUE THREAD

**Issue by haf** [haf/expecto#287]
![image](https://user-images.githubusercontent.com/193115/47078822-6b7f3100-d204-11e8-9f69-4f60f5bccdeb.png)

The world is so grey now. Is this intended @AnthonyLloyd ?

**Comment by AnthonyLloyd** [comment]
No, I matched up the colors as best I could from the logger to ANSI. Will take a look later.

**Comment by haf** [comment]
@AnthonyLloyd Thank you, I must admit I just found the culprit and it was my own fault primarily. But I think this change is really good:

<img width="236" alt="screen shot 2018-10-20 at 15 48 51" src="https://user-images.githubusercontent.com/193115/47256378-b193f900-d47f-11e8-8de8-5a378e150c8a.png">

**Comment by haf** [comment]
Also, this is what it looks like without 51113bc, on black backgrounds


<img width="236" alt="screen shot 2018-10-20 at 15 48 51" src="https://user-images.githubusercontent.com/193115/47256424-7c3bdb00-d480-11e8-9e7e-06843792e1d9.png">
