### ISSUE TITLE
Expecto fails silently on duplicate tests

### ISSUE THREAD

**Issue by otto-gebb** [haf/expecto#299]
Steps to reproduce:

1. Create a test project with two tests with the same name.
2. Do `dotnet run` in project folder.

Observed behavior: no console output, exit code 1.

Expected behavior: a message like this in the console

```
[01:38:31 ERR] Found duplicated test names, these names are: [samples/duplicate] <Expecto>
```

Known workaround: downgrade the package to v8.6.0. (Bug was introduced in v8.6.3)

**Comment by AnthonyLloyd** [comment]
Thanks will take a look as soon as I can. On holiday at the moment.
