### ISSUE TITLE
String diff support

### ISSUE THREAD

**Issue by haf** [haf/expecto#3]
Make output like this easier to parse for humans, by showing at what position the strings differ:

```
Should have both the fields as values, and the default value.. Actual value was "Processor.%\ Utilisation,unit=% Core\ 1=0.03,Core\ 2=0.06,Core\ 3=0.139,value=1i 1435362189575692182" but had expected it to be "Processor.%\ Utilisation,unit=% Core\ 1=0.03,Core\ 2=0.06,Core\ 3=0.139,value=1i 1435362189575692182".
```

**Comment by cloudRoutine** [comment]
I've always found FParsec's  error messages particularly satisfying
```
Error in Ln: 1 Col: 10
[1] [2] [c]
         ^
Expecting: integer number (32-bit, signed)
```
so maybe something like

```
[Expected value was]                              
"Processor.%\ Utilisation,unit=% Core\ 1=0.03,Core\ 2=0.06,Core\ 3=0.139,value=1i 1435362189575692182"
                                                          ↑                                                    
                                                Error in Col: 59
[Actual value was]                                        ↓
"Processor.%\ Utilisation,unit=% Core\ 1=0.03,Core\ 2=0.06;Core\ 3=0.139,value=1i 1435362189575692182"
```

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/21313840/5fb130c6-c5f4-11e6-91f9-fdf3ebd1018e.png)

it should at least report both strings - not only first char

**Comment by Krzysztof-Cieslak** [comment]
I guess we could display both strings, and then report 1st (all?) position on which they differ.

**Comment by forki** [comment]
yes please display at least the actual value. the expected vaue I can find in the code, but the actual value is definetly only in the app

**Comment by MNie** [comment]
Hi,

something like that is ok?
![image](https://cloud.githubusercontent.com/assets/7689103/21433461/2e6d6bb4-c870-11e6-8e64-15968683c785.png)

**Comment by Krzysztof-Cieslak** [comment]
I wouldn't use `[` and `]` since it's not used anywhere else. 

But otherwise, looks good to me.
