### ISSUE TITLE
Output sometimes hard to read

### ISSUE THREAD

**Issue by dlidstrom** [haf/expecto#304]
It seems that Expecto varies the output depending on the type of failure. For some types of failures, this makes the output hard to read. For other types of failures the output is easy to read.
For an example of what is easy to read:

![expecto-good](https://user-images.githubusercontent.com/371713/52337579-4e1ae080-2a08-11e9-9c0b-f3f0dd547451.PNG)

The output above is clearly stating what is expected and what is actual.

Now to an example of what I consider hard to read:

![expecto-bad](https://user-images.githubusercontent.com/371713/52337660-8c180480-2a08-11e9-8b18-b0c4001a1683.PNG)

Here it is much harder to see what is expected and what is actual, even if the output in this case is quite small. The order of expected/actual even differs from the first example which is confusing IMO. At the least, a line break before "but had expected it to be" would be more clear.
Can this be improved to be shown as the first example for all kinds of failures?

**Comment by AnthonyLloyd** [comment]
I can make it a bit more consistent. Nested diff position is a bit more tricky but could be possible.

**Comment by AnthonyLloyd** [comment]
@dlidstrom I've make this more consistent and underlined differences in Expected and Actual. Let me know if you see anything else.
