### ISSUE TITLE
Colors are a bit off

### ISSUE THREAD

**Issue by forki** [haf/expecto#305]
type R = { Name : string; Age: int}

    type R = { Name : string; Age: int}

    let MyTTests =
      testList "records" 
        [

          testCase "show how records differ" (fun _ ->
            let r1 = { Name = "Steffen"; Age = 35 }
            let r2 = { Name = "Steffen"; Age = 36 }
            Expect.equal r1 r2 "only age is different"
          )
        ]

results in:

![image](https://user-images.githubusercontent.com/57396/53477227-872cfa80-3a74-11e9-96ec-30af22c3033b.png)

I'd assume only the 6 is green and only 5 is red!?

**Comment by AnthonyLloyd** [comment]
Will check. May need to off it and then set set it to the subtext colour to cover all terminals.

**Comment by forki** [comment]
thanks mate

**Comment by AnthonyLloyd** [comment]
NP

**Comment by haf** [comment]
This is not fixed yet; with latest Expecto

<img width="846" alt="image" src="https://user-images.githubusercontent.com/193115/55577037-e7b5f400-5712-11e9-9eb4-1d44aa88ae15.png">

**Comment by haf** [comment]
Also, the colours as printed on dark backgrounds are bad for readability; we should use pastel colours, not primary ones.

**Comment by AnthonyLloyd** [comment]
It looks ok to me. Which part is wrong? 

--colours 256 will give those colours.

**Comment by haf** [comment]
@AnthonyLloyd The red part with blue mixed in?

**Comment by haf** [comment]
> --colours 256

This should be the default. If your terminal doesn't support it, you can opt out.

**Comment by AnthonyLloyd** [comment]
That's where the text at that position matches. Its going to happen even in random text. Would need a smarter diff algo. Maybe if just one char is diff in largw patch.

**Comment by haf** [comment]
Oh I see. I've never seen this diff algo beforee. Closing.
