### ISSUE TITLE
Make `foldCLIArgumentToConfig` public

### ISSUE THREAD

**Issue by TheAngryByrd** [haf/expecto#307]
With the [PR from the VSTestAdapter being able to pass in configuration to Expectp]( https://github.com/YoloDev/YoloDev.Expecto.TestSdk/pull/21#discussion_r264309117), we had to copy and paste the implementation of  `foldCLIArgumentToConfig` with tweaks to make it work. From this adapters point of view it would be nice to just leverage this function rather than having a copy. If you think this is acceptable I can do the PR.

**Comment by AnthonyLloyd** [comment]
I'm hoping to make ExpectoConfig internal. I'll take a look at the adapter but is it not possible to provide a list of CLiArguments to a runTests function?

**Comment by TheAngryByrd** [comment]
Oh you're thinking `runTestsWithCLIArgs `? I overlooked that.  I think that would work just fine 👍

**Comment by AnthonyLloyd** [comment]
cool
