### ISSUE TITLE
Expect length of a list/sequence asserter?

### ISSUE THREAD

**Issue by drhumlen** [haf/expecto#311]
I seem to miss an expect function like:

```F#
let list = [1; 2; 3; 4]
Expect.lengthOf list 3 "Must have exactly 3 elements"
```

If it fails, I expect to see something like:

```
Expected length to be 3, but: 

[1; 2; 3; 4]

has length 4.
```

Is there another way to do this or..? Seems like a quite fundamental asserter.

**Comment by AnthonyLloyd** [comment]
There isn't an expect function for this. It sound good. Could you add a PR?

**Comment by drhumlen** [comment]
Done: https://github.com/haf/expecto/pull/312/files 😄

**Comment by AnthonyLloyd** [comment]
Thanks
