### ISSUE TITLE
Skipping results in an exception report

### ISSUE THREAD

**Issue by et1975** [haf/expecto#313]
Using 8.10.0 and skipping a task test:

>[14:23:10 ERR] [snip] errored in 00:00:00.0020000 <Expecto>
Expecto.IgnoreException: skipped
   at [snip]
   at FSharp.Control.Tasks.TaskBuilder.run[a](FSharpFunc`2 firstStep) in C:\Users\humbo\source\repos\TaskBuilder.fs\TaskBuilder.fs:line 226

**Comment by AnthonyLloyd** [comment]
Sorry, I can't reproduce. Can you give more details or an example.

**Comment by et1975** [comment]
I have this:
`let noop = task { Tests.skiptest "skipped" }`
which used to work as expected in 8.6.0, now it seems to fall through.

**Comment by AnthonyLloyd** [comment]
I'm not sure what changed but the ignore ends up in an AggregateExpception and then isn't considered as an ignore.

Easy enough to put in a check.
