### ISSUE TITLE
Progress log does not flush on test completion

### ISSUE THREAD

**Issue by et1975** [haf/expecto#314]
Upgraded from 8.6.0 to 8.10.0 and see that default console log does not flush anymore while the test are running. Only the spinner is visible until a failure occurs, then everything up to that point is flushed until the next error or the termination.

**Comment by AnthonyLloyd** [comment]
I think this is by design. I guess it could be changed or configured.

Do you have test output you want to see? How do you produce the output?

**Comment by et1975** [comment]
I'm talking about messages produced by Expecto itself, this kind of logs:
>[14:23:21 DBG] group/test starting... <Expecto>
[14:23:26 DBG] group/test passed in 00:00:05.0650000. <Expecto>

Used to appear as things happened, now... only on error or termination.

**Comment by AnthonyLloyd** [comment]
Ah, with --debug. That sounds reasonable.

**Comment by AnthonyLloyd** [comment]
I've fixed this. It is meant to do this but there is some hairy logging logic.

Let me know if these 2 changes are urgent or not for you. I may release soon or in the next week or so.

**Comment by et1975** [comment]
Next week would be great, thank you so much!

**Comment by AnthonyLloyd** [comment]
released in v8.10.1
