### ISSUE TITLE
Adopt SemVer

### ISSUE THREAD

**Issue by slang25** [haf/expecto#319]
Hi, the latest release has broken [YoloDev.Expecto.TestSdk](https://github.com/YoloDev/YoloDev.Expecto.TestSdk) due to an addition to the `ExpectoConfig` record.

Could the major version be bumped in future cases of this, or is there a better way to protect from this on the other end?

**Comment by AnthonyLloyd** [comment]
We have moved to a CLIArguments DU command line so config can be added without needing a major version. I think TestSdk is in the process of migrating.

**Comment by slang25** [comment]
Brilliant 🙂 you're right it is. Thanks
