### ISSUE TITLE
Warning on config record: `parallel` is reserved for future use by F#

### ISSUE THREAD

**Issue by adz** [haf/expecto#328]
Using the `parallel` setting in a config results in a compiler warning:

    warning FS0046: The identifier 'parallel' is reserved for future use by F#

It's annoying to have a warning, but in future, I guess it could break.

I suppose it should be changed?

**Comment by AnthonyLloyd** [comment]
Yes, thanks for pointing it out. I'm keep this around to note this should be done on a major version.
