### ISSUE TITLE
Strange control codes emitted by Expecto in DevOps

### ISSUE THREAD

**Issue by isaacabraham** [haf/expecto#334]
Running a standard Expecto run that works fine locally but in Azdo I see lots of what appears to be encoded characters e.g. `&gt`. I'm not sure why this is, but I only see this with Expecto. Is there something that might be causing it and / or that can be disabled?

![image](https://user-images.githubusercontent.com/1781813/61581166-fc2fc800-ab1a-11e9-8842-121507dd3fd5.png)

cc @theimowski not sure if there's anything in the SAFE build that might be causing this?

**Comment by haf** [comment]
Seems like you have XML encoded characters further up than expecto as well. Since Expecto doesn't print XML other than for the nunit output, it's not Expecto.
