### ISSUE TITLE
Make expectation message string optional

### ISSUE THREAD

**Issue by PhilT** [haf/expecto#361]
In other test frameworks, it's not a requirement to have a message string for each expectation. In many scenarios it is redundant.

I'm new to F# and Expecto so perhaps this would break something but it'd be nice to be able to do something like:

```fsharp
Expect.equal (1 + 1) 2
```

From what I've seen, Expecto generates a suitable message if failure occurs.

**Comment by FoggyFinder** [comment]
Exactly. Messages are very clear by themselves and for many cases there is no need in any additions.

**Comment by haf** [comment]
You can just define:

```fsharp
module Expect =
  let equal a b = b |> Expect.equal "" a
```

So I think I'll mark this as won't-fix since it's pretty quick to add a ` ""` after your sample or do the above.

**Comment by haf** [comment]
That said, I have a huge improvement inbound, and if this is still an issue after that we can look into it.

**Comment by PhilT** [comment]
Thanks. I thought there might be a simple workaround.

Cool! Looking forward the updates.

**Comment by rahicks26** [comment]
Just following up, to see if these would still be a nice feature? Our team is really interested in it and we would be willing to contribute.

**Comment by haf** [comment]
@rahicks26 What's your thinking? Making all functions overloaded? Perhaps we can talk API surface area a bit before we move forward?

**Comment by rahicks26** [comment]
I hadn't given it too much thought just yet to be honest. Let me review it a bit this week and get back to you. We love the project and it has really helped us a lot here recently.

**Comment by rahicks26** [comment]
@haf So after some review, we might be able to solve this by making it possible for tests to return `unit` or `string->unit`. Not sure if that is being tracked somewhere else or not. We can assume if `string -> unit` is returned the default message should be an empty string.

**Comment by haf** [comment]
The thing with that suggestion (returning a function `string -> unit`) is that you can't vary the return type of functions in F#, and besides that, it would only work if you only have a single assert that is also the last expression of the function.

Feel free to play around and see if you can find an API that works, it would be interesting to see.

**Comment by lydell** [comment]
Hi! Sorry for posting in this old thread. Are there any examples out there with inspiration on what what to write in the `message` parameter? My mind always goes blank on it, and I’m wondering if I’m missing out on something.

**Comment by haf** [comment]
Have a look at https://github.com/logary/logary 's test suite — perhaps that can give you some inspiration?
