### ISSUE TITLE
Is there a way to run all tests with shuffle?

### ISSUE THREAD

**Issue by PhilT** [haf/expecto#363]
It seems you can either choose to use self-discovering tests with `<[Tests]>` and `runTestsInAssemblyWithCLIArgs` or be able to shuffle them but have to specify them explicitly.

```
myTests // from MyLib.Tests
|> Test.shuffle
|> runTestsWithCLIArgs [] [||]
```

Is there a way to shuffle auto-discovered tests?

**Comment by haf** [comment]
You could shuffle them on start, where you assign them, but no, right now there's no way to do that.

**Comment by ZaymonFC** [comment]
[This example](https://github.com/ZaymonFC/ToyRobot/blob/master/src/Test/Program.fs) may help although I am not entirely sure. 

The project uses [this method](https://www.daniellittle.dev/) to hook into the standard `dotnet test` discovery.

**Comment by PhilT** [comment]
Thanks @ZaymonFC, that is close but it means specifying every module. I'm not familiar with .NET but I imagine there is a way to use reflection to grab all the modules in the test project and use that method to shuffle them. I'll investigate.

**Comment by PhilT** [comment]
That was easier than I was expecting!

```fsharp
open Expecto
open System.Reflection

let assembly = Assembly.GetExecutingAssembly()

let testsFromModules =
  assembly.GetTypes()
  |> Seq.filter (fun t -> t.ToString().StartsWith("ToplevelModuleName") && t.ToString().EndsWith("Test"))
  |> Seq.map (fun t -> (box (t.GetMethod("get_tests").Invoke(null, [||]))) :?> Test)
  |> Seq.toList

[<Tests>]
let tests =
  testList "Engine" testsFromModules
  |> Test.shuffle

[<EntryPoint>]
let main argv =

    printfn "Running tests!"

    let config =
        { defaultConfig with
            verbosity = Logging.LogLevel.Verbose
            colour = Logging.Colour256
            fsCheckMaxTests = 100
        }

    runTestsWithArgs config argv tests
```

I just need to change the StartsWith filter to be a bit more generic and then we can think about possibly adding this in to Expecto?

**Comment by PhilT** [comment]
This is a bit more generic:

```fsharp
open Expecto
open System.Reflection

let testsFromModules =
  let assembly = Assembly.GetExecutingAssembly()

  assembly.GetTypes()
  |> Seq.filter (fun t -> t.Name <> "Program") // Ignore current file
  |> Seq.map (fun t ->
    match t.GetMethods() |> Array.tryFind(fun m -> m.Name = "get_tests") with
    | Some func -> Some ((box (func.Invoke(null, [||]))) :?> Test)
    | None -> None
  )
  |> Seq.choose id
  |> Seq.toList

let tests =
  testList "Engine" testsFromModules
  |> Test.shuffle

[<EntryPoint>]
let main argv =

    let config =
        { defaultConfig with
            verbosity = Logging.LogLevel.Verbose
            colour = Logging.Colour256
            fsCheckMaxTests = 100
        }

    runTestsWithArgs config argv tests
```

**Comment by haf** [comment]
Nice!

I'm closing this for now, as the feature as such is a bit unclear. I'd love to improve expecto generally, but it has to be "needed" to avoid adding extra features for the sake of it. A nice PR could convince me ;)
