### ISSUE TITLE
 Use dot as a separator instead of slash

### ISSUE THREAD

**Issue by cmeeren** [haf/expecto#364]
Originally posted in https://github.com/YoloDev/YoloDev.Expecto.TestSdk/issues/26, but I was redirected here.

When the VS test explorer renders the test tree, it seems to use dot as a separator (if grouping by namespace/class).

Consider the following tests:

```f#
[<Tests>]
let tests =
  testList "Domain" [
    testList "Username" [
      testList "create" [
        testCase "returns Error if input is empty" ignore
        testCase "returns Error if input length is > 100" ignore
        testCase "trims the input if Ok" ignore
      ]
    ]
    testList "CustomerNumber" [
      testList "create" [
        testCase "returns Error if input is empty" ignore
        testCase "returns Error if input is non-numeric" ignore
        testCase "returns Ok if the input is numeric" ignore
      ]
    ]
  ]
```

Test Explorer shows it like this:

![image](https://user-images.githubusercontent.com/7766733/68758044-59411380-060d-11ea-8add-572661847708.png)

All tests appear in a flat list. This makes it hard to read, hard to find relevant tests, and hard to select a related group of tests to run.

It would be much more useful if Test Explorer could show it as a tree. AFAIK this would only require using `.` instead of `/` as a separator in the hierarchy.

It can be worked around to some extent by adding dots to the end of each test list name:

```f#
[<Tests>]
let tests =
  testList "Domain." [
    testList "Username." [
      testList "create." [
        testCase "returns Error if input is empty" ignore
        testCase "returns Error if input length is > 100" ignore
        testCase "trims the input if Ok" ignore
      ]
    ]
    testList "CustomerNumber." [
      testList "create." [
        testCase "returns Error if input is empty" ignore
        testCase "returns Error if input is non-numeric" ignore
        testCase "returns Ok if the input is numeric" ignore
      ]
    ]
  ]
```

![image](https://user-images.githubusercontent.com/7766733/68758297-d66c8880-060d-11ea-8b01-30855002b581.png)

But it's not optimal: It requires changing the names, it still renders the slashes, and seems to only work for the last levels (e.g. `Domain./CustomerNumber` hasn't been split, and if there are single sibling test cases of nested tests lists, then they are not shown grouped in the same way).

If Expecto could support using `.` instead of `/` as a separator, I think that would give a much better experience in the VS test explorer. 🙂

Or if you have any other idea about how to improve this, that would be great!

---

Just to be clear about the sibling test stuff I mentioned, in case it's relevant:

```f#
[<Tests>]
let tests =
  testList "Domain." [
    testList "Username." [
      testCase "Some other username test" ignore
      testList "create." [
        testCase "returns Error if input is empty" ignore
        testCase "returns Error if input length is > 100" ignore
        testCase "trims the input if Ok" ignore
      ]
    ]
    testList "CustomerNumber." [
      testList "create." [
        testCase "returns Error if input is empty" ignore
        testCase "returns Error if input is non-numeric" ignore
        testCase "returns Ok if the input is numeric" ignore
      ]
    ]
  ]
```

![image](https://user-images.githubusercontent.com/7766733/68758865-e3d64280-060e-11ea-942c-4de5ddbde73f.png)

**Comment by haf** [comment]
Solved in #366

**Comment by cmeeren** [comment]
Hooray! Looking forward to release 😁 But will #366 alone fix the issue? Based on very cursory reading of that PR, it seems like there is a new option with a default value of `/`. But the VS test runner (or YoloDev.Expecto) doesn't use that, right?

**Comment by haf** [comment]
@cmeeren This is true, but now it can use it. It should be a very minor change to PR that for YoLoDev

**Comment by cmeeren** [comment]
Nice! So that means it should automatically work once I update expecto, with no changes required on YoloDev's part?

**Comment by haf** [comment]
<img width="647" alt="Screenshot 2020-04-04 at 11 43 58" src="https://user-images.githubusercontent.com/193115/78423857-97e17400-7669-11ea-8fd9-9132ef417608.png">

Well, it's a major release, so there are breaking changes to the API, but we've kept them to a minimum. Let's see ;)?
