### ISSUE TITLE
Latest version fails to find FsCheck

### ISSUE THREAD

**Issue by Shmew** [haf/expecto#371]
Using the latest version of expecto I get the following error when I try to run my tests:

![image](https://user-images.githubusercontent.com/11186595/76151290-0afec700-6079-11ea-8ed9-ac0a000673a3.png)

**Comment by Shmew** [comment]
Just for anyone else coming across this in the meantime: I was able to resolve this for now with a binding redirect to 2.14.0.

**Comment by haf** [comment]
@Shmew What you're describing is the 'default' workflow for .net projects. Your issue here is that Expecto would need to bump its dependency for the 'default happy path'; it's a `paket upgrade` call away, hence the "easy" label.

**Comment by haf** [comment]
Solved in #372
