### ISSUE TITLE
Report test execution time

### ISSUE THREAD

**Issue by teo-tsirpanis** [haf/expecto#373]
My project has fifty tests. I observe the test runner to take some more time at one of them, but I have no idea which of them is the culprit.

Is there any way to view that? If not, a good implementation idea would have been to display execution time in the test summary, or even better create XML test reports like NUnit.

**Comment by haf** [comment]
You could enable the xml reporting?

**Comment by teo-tsirpanis** [comment]
Oh, I didn't know at all about that. I just saw the `Expecto.TestResults` NuGet package.

Thanks. Keep up the good work!
