### ISSUE TITLE
TeamCity reporting

### ISSUE THREAD

**Issue by theimowski** [haf/expecto#39]
Add ability (command line option?) to format the output so that [TeamCity can understand it](https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-Supportedtestservicemessages). 

[Here](https://github.com/xunit/xunit/blob/master/src/xunit.runner.reporters/TeamCityReporterMessageHandler.cs)'s how xUnit does it.

I'm willing to contribute - any tips?

**Comment by Krzysztof-Cieslak** [comment]
Adding it should be easy:

Step 1. Create custom printer - https://github.com/haf/expecto/blob/master/Expecto/Expecto.fs#L320-L424
Step 2. Create flag turning it on - https://github.com/haf/expecto/blob/master/Expecto/Expecto.fs#L823

**Comment by adamchester** [comment]
@theimowski you may also need to use a [different configuration](https://github.com/haf/expecto/blob/fcca2aa8fa94ff84f0770b46f28fbee12729aa60/Expecto/Expecto.fs#L849) for the [Logary Facade](https://github.com/logary/logary/blob/master/src/Logary.Facade/Facade.fs). Perhaps the [`TextWriterTarget`](https://github.com/logary/logary/blob/66b76e5e4c552e61c356fb3d935d714778b872bb/src/Logary.Facade/Facade.fs#L712) would help?

**Comment by haf** [comment]
@adamchester I think TC just collapses colourisation though, so we probably don't need another config?

**Comment by adamchester** [comment]
@haf I'm guessing a problem might be the [hard-coded line prefix](https://github.com/logary/logary/blob/master/src/Logary.Facade/Facade.fs#L623)

**Comment by haf** [comment]
@adamchester True that. Delegator pattern could work though.

**Comment by theimowski** [comment]
@haf not sure I get the delegator idea - what would we delegate to?
TC expects following entry: `##teamcity[testFinished name='testName' duration='<test_duration_in_milliseconds>']`

**Comment by haf** [comment]
@theimowski The existing result printer. Wrapping it in one that simply takes the console lock from `Expecto.Logging.Globals.consoleSemaphore` and prints the above.
