### ISSUE TITLE
enhancement: list focused tests

### ISSUE THREAD

**Issue by vilinski** [haf/expecto#392]
To be sure the test suite runs all tests I use the `--fail-on-focused-tests` flag

```
$ dotnet run -- --fail-on-focused-tests
[10:13:11 ERR] It was requested that no focused tests exist, but 1 focused tests were found. <Expecto>
```
The output message is unhelpful. Luckily I can grep for `ftest`, but it is not ideal
Better were to see which tests are focused to unfocus them again.
Is it possible to list them instead of pointing out there are some?

Maybe also something similar for pending tests?

**Comment by haf** [comment]
Good enhancement suggestion! 👍
