### ISSUE TITLE
DiffEngine

### ISSUE THREAD

**Issue by SimonCropp** [haf/expecto#398]
@haf 

So I built a thing https://github.com/VerifyTests/DiffEngine

It allows for convention based detection and launch of a number of diff tools https://github.com/VerifyTests/DiffEngine/blob/master/docs/diff-tool.md#supported-tools

I was wondering if this would be useful to expecto?

I was thinking expecto could launch and close diff tools when a test fails or succeeds?

Is this something that would interest you? If so i am happy to pair with you to work on. Unfortunately i lack the skill in f# to submit a PR on my own.

**Comment by haf** [comment]
So there's an abstraction in Expecto for diffing; it gets invoked with the two bodies to diff; and with `Expecto.Diff` you get nice output from this.

As such, Expeco doesn't create files by itself. A plugin like you describe would have to create those files.

I'm actually not sure how wanted this would be; I've managed 6 years with a lot of tests written in Expecto without needing a tool like this, but I'm not sure others would agree. Have you done some market research about what people want?

**Comment by SimonCropp** [comment]
fair enough. if you dont think it is useful, then probably not worth the effort

**Comment by haf** [comment]
I may not be your target audience, but I want expecto to cater for many different audiences. If you find it useful or you have a good use case I’m open to discussion. The door to converse about this is always open. 👌
