### ISSUE TITLE
Weird summary in expecto 2.3

### ISSUE THREAD

**Issue by forki** [haf/expecto#41]
![image](https://cloud.githubusercontent.com/assets/57396/21520652/3f7cb66e-ccf6-11e6-965c-0fb9f427d23b.png)

/cc @Krzysztof-Cieslak

**Comment by Krzysztof-Cieslak** [comment]
Git blame tells me it was @haf, not me ;P https://github.com/haf/expecto/blame/master/Expecto/Expecto.fs#L404-L408

**Comment by forki** [comment]
ok even if my command line would show proper unicode, I would have real trouble understanding that spirit. I know it's less fun, but can we change it to a red / green english word?

**Comment by haf** [comment]
You need a terminal capable of UTF8. It's soon 2017 after all ;) ┳━┳ ヽ༼ಠل͜ಠ༽ﾉ

**Comment by haf** [comment]
@forki There's no 'use' for the spirit; the preceding stats tell the whole story.

**Comment by forki** [comment]
Ok. I don't want to play party pooper. But can we remove it?

**Comment by haf** [comment]
Why?

**Comment by haf** [comment]
Can't we just make a config option to turn them off?

**Comment by forki** [comment]
I'm trying to introduce expecto into the business side. Such features are
not really making my life easier. I will send a Pull request with a
proposal for replacement

Am 28.12.2016 12:29 schrieb "Henrik Feldt" <notifications@github.com>:

Can't we just make a config option to turn them off?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/haf/expecto/issues/41#issuecomment-269464749>, or mute
the thread

**Comment by Krzysztof-Cieslak** [comment]
I'd vote for turning it off by default. adding flag if someone wants them.

**Comment by forki** [comment]
> You need a terminal capable of UTF8. It's soon 2017 after all ;)

that's the one you get by running from VS with ctrl+F5

**Comment by Krzysztof-Cieslak** [comment]
> that's the one you get by running from VS with ctrl+F5

You can change it to powershell, as far as I remember ;)

**Comment by forki** [comment]
yes I think this will do. thanks
