### ISSUE TITLE
Move to fsprojects?

### ISSUE THREAD

**Issue by Lanayx** [haf/expecto#430]
@haf Hi, it seems you are not actively supporting the project, would you mind moving it into [fsprojects ](https://github.com/fsprojects) organization to give it a new life? Expecto is a great product in many ways, but without support it won't last long.

**Comment by haf** [comment]
Hi

Why can’t you send PRs here?

It seems the project has lasted long without my active development. 

Cheers

**Comment by Lanayx** [comment]
You see, there are 3 open PRs, where latest didn't receive any feedback from you. I would't create a new PR when noticed that. There are also many issues without comments - such irresponsiveness will keep people away of working on the project. At the same time there are quite a few people using it and some may be able to support the project if it was under the fsprojects umbrella.

**Comment by haf** [comment]
There was only one PR I had missed, the latest one. ;)

This is OSS, so are you interested in maintaining the project? :)
