### ISSUE TITLE
Print current test

### ISSUE THREAD

**Issue by forki** [haf/expecto#44]
I have a testsuite that runs for a while. it would be nice if expecto would print status of every test after it is run

**Comment by haf** [comment]
`--debug` gives you that.

**Comment by forki** [comment]
that is a bit weird. usually this should be the default since we need to know if things are still running. even on CI server the progress is important.

**Comment by haf** [comment]
The default for me is that I have a huge number of tests and I can't find the failing ones if they're all printed. So I think the optimal outcome is for the executable only to print a single line if everything succeeds and nothing is ignored. Any other behaviour should be opt in according to the unix principle of single-purpose processes that only output relevant information. SSH works the same way, to pick a random example.

**Comment by haf** [comment]
That said; how about a feature that prints progress?

**Comment by forki** [comment]
I'm so hoping you do that ;-)

2016-12-29 18:33 GMT+01:00 Henrik Feldt <notifications@github.com>:
