### ISSUE TITLE
Most test types are discoverable by test explorer, but `testTask` type is not

### ISSUE THREAD

**Issue by drk-mtr** [haf/expecto#445]
When using the test explorer in VS code, tests that use the `test` or `testAsync` approach are picked up fine as expected, but tests of type `testTask` are not.

![image](https://user-images.githubusercontent.com/40315783/226207777-4ea0961c-a74a-496b-9574-ee6c45d35371.png)

This could well be user error or unsupported functionality in the VS Code test explorer, rather than an Expecto issue specifically, because in Visual Studio I can see `testTask` tests (even if their names are built programmatically, which is rather impressive).

## Repro

1. Create new project using `dotnet new expecto`.
2. Open project in VS code.
3. Run `dotnet build`.
4. Add a test of type `testTask` to the samples test list.

Expected: All tests including `testTask` are discovered i.e. can be run via UI.
Actual: `testTake` cannot be run, others can.

## Notes

Issue also present in Visual Studio.

Versions:
- Expecto v9.0.4
- YoloDev.Expecto.TestSdk v1.0.0
- Microsoft.NET.Test.Sdk v17.5.0
- VS code 1.76.2

## Workaround

This works but is not ideal:

```fsharp
testAsync "this is a task test" {
    return! task {
        let! n = Task.FromResult 2
        Expect.equal n 2 "n=2"
    } |> Async.AwaitTask
}
```

Thanks for the brilliant library!

**Comment by ratsclub** [comment]
@baronfel Oh, I didn't know about that, I guess the fix is really simple then!

**Comment by ratsclub** [comment]
@baronfel I opened the PR there.

**Comment by ratsclub** [comment]
@drk-mtr The fix should be included in FsAutoComplete's next release.

**Comment by drk-mtr** [comment]
Brilliant, thank you!

**Comment by Numpsy** [comment]
Hi,
I'm not sure if this is an issue here, or in Ionide or FSAutoComplete, but - I seem to have a similar situation with ```testTheory``` - 
The test explorer pane is listing the tests from the testTheory, but the editor window has no markers for the test, and right click -> run tests at cursor seems to either run everything in the test list, or just the previous test case in the file

![image](https://github.com/haf/expecto/assets/1178570/2cd65930-4a02-43c8-b0e6-ca06cd512efc)


I thought this was maybe the same situation as the op, where FsAutoComplete needs to be taught to recognize 'testTheory' but then I see that Ionide has recently had a rework to how test discovery works, so I'm not sure where the responsibility lies.

Thanks

**Comment by farlee2121** [comment]
@Numpsy `testTheory` items show in the explorer due to the new changes that base the explorer on test result.
The code locations of tests are still found exclusively through code analysis. A code location is necessary for the gutter decorations you noticed as missing.

In short, this is the same issue as before. [This method](https://github.com/fsharp/FsAutoComplete/blob/daf36195bf0295b075dac7be81e51f9f0a277eb5/src/FsAutoComplete.Core/TestAdapter.fs#L43) in the code analyzer needs to be looking for `testTheory`.

**Comment by Numpsy** [comment]
Ok, thanks.
I can see about doing a PR for it, if no one else gets to it before I manage to build FsAutoComplete (never tried before)

**Comment by baronfel** [comment]
@Numpsy yes, we'd love any and all enhancements to the test discovery in FSAC!

**Comment by Numpsy** [comment]
Ok, my tests are getting highlighted now ith Ionide 7.11: 

![image](https://github.com/haf/expecto/assets/1178570/d10d2078-ddbb-4319-942a-6334144d19eb)
