### ISSUE TITLE
Expecto.Scientist? Expecto.Hypothesis?

### ISSUE THREAD

**Issue by cloudRoutine** [haf/expecto#5]
I'm not especially familiar with either of these test frameworks, but they seem to have some interesting ideas. Maybe some of them could be extracted for Expecto?

https://github.com/github/Scientist.net

https://hypothesis.readthedocs.io/en/latest/

**Comment by haf** [comment]
What does it add on top of FsCheck?

**Comment by cloudRoutine** [comment]
Something akin to [the hypothesis example database](https://hypothesis.readthedocs.io/en/latest/database.html) seems like it could be useful in concert with FsCheck where complicated and expensive generators or extremely large numbers of tests need to be run.

FsCheck doesn't really have the plugs and connectors to make it great OOB for integration testing, end-to-end testing, critical path testing, which is what Scientist is oriented toward.

This is where I can see expecto coming in with the tools and components to help orchestrate bigger more systemic styles of testing with FsCheck as an engine inside of it generating input data and [models](https://hypothesis.readthedocs.io/en/latest/database.html) inside the tracks that expecto has laid down.  All the while providing logging and analysis capabilities to give back error reports that make it easier to understand what, when, and why something went wrong.

Sorry if this is too vague or unclear, I haven't totally worked it out in my head yet.

**Comment by haf** [comment]
This could probably be done with https://github.com/kurtschelfthout/FsLogic and forwards-inference over protocol definitions as well.
