### ISSUE TITLE
`--summary` not working

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [haf/expecto#53]
`--summary` flag is not working for me any more on latest version - this bug is reproduced in latest builds on Travis.  Last build which is displaying summary is https://travis-ci.org/haf/expecto/jobs/188807194 (for 6fd15ac33d1cb5d42e766d613e710e7bc53de91c), next one is not displaying summary any more (https://travis-ci.org/haf/expecto/jobs/188808798).... But it doesn't make any sense for me since dd99ef503f02b0ddf25ea55e825b7332f8bc1e86 (commit for which build is not displaying summary anymore) was just version bump, without any changes in code.

@haf, any ideas?

**Comment by haf** [comment]
It's because someone at some point the last couple of days PRed `Async.Start` into the code. I saw it but, hey, this is a unit-testing lib, so if bugs come in, then they should be unit-tested away by even more PRs ;)

**Comment by Krzysztof-Cieslak** [comment]
CC: @AnthonyLloyd  ;)

**Comment by haf** [comment]
We can just make it `RunSynchronously` for now, until #2 is done.

**Comment by Krzysztof-Cieslak** [comment]
I'll change it in #47

**Comment by Krzysztof-Cieslak** [comment]
Or not, either I'm going crazy or changing it to `RunSynchronously` doesn't fix the problem

**Comment by AnthonyLloyd** [comment]
Maybe I should take a look...

Will do tonight if not fixed by then.
