### ISSUE TITLE
[Feature Request] Surface Area/Semantic Versioning Testing

### ISSUE THREAD

**Issue by cloudRoutine** [haf/expecto#6]
It'd be nice to have a way to make sure that updates to a project aren't breaking semantic versioning rules. This could be validated by storing the metadata for a project's public API and checking against it. Maybe it could run in an analytic mode just to tell you what the version upgrade should be based on the current state of the assembly vs the stored metadata?

The offending changes, or just the analytic output could be presented as a signature diff across the public api [kind of like this one for the netstandard changes](https://gist.github.com/cloudRoutine/0ae9f5ec1cf3bdc6b7fd36576af013ef)

Would this be an appropriate feature for expecto?

**Comment by haf** [comment]
Sounds like a great feature!

**Comment by wallymathieu** [comment]
There is a project that aims to get the major, minor and patch version difference based on surface area:
https://github.com/fsprojects/SyntacticVersioning
In order to pool the effort previously done in:
https://github.com/wallymathieu/SemVer.FromAssembly
and in:
https://github.com/spisemisu/SpiseMisu.SemanticVersioning

**Comment by cloudRoutine** [comment]
Yea there was an [F# Advent 2016 article on it too](http://blog.stermon.com/articles/2016/12/01/semantic-versioning-dotnet-libs-and-nuget-pkgs)

**Comment by haf** [comment]
Could you amend the issue with a suggestion on how to do it? We'd need an abstraction for storing data across tests and DotNetBenchmark's results folder should probably go inside that abstraction as well.

**Comment by wallymathieu** [comment]
One way would be to contribute to 
https://github.com/fsprojects/SyntacticVersioning/

I'm doing a bit of merging of the libraries. A textual representation is done by @gentauro : https://github.com/fsprojects/SyntacticVersioning/blob/master/tests/ExampleProjects/src/Fsharp2.txt

**Comment by gentauro** [comment]
@cloudRoutine once I published my blog post, @wallymathieu mentioned that he had something similar (only for `.NET` assemblies but not `NuGet` packages).

This is why we agree to join efforts in combining the two libraries into one and put it under the F# Projects roof.

**Comment by haf** [comment]
@gentauro That sounds super. What do you guys think should be the story for Expecto users then? An `Expect.followsSemver asm history "Should follow semver"` call?

**Comment by wallymathieu** [comment]
We have discussed a way to enable that scenario in : 
https://github.com/fsprojects/SyntacticVersioning/issues/5
