### ISSUE TITLE
Expecto doesn't have a version

### ISSUE THREAD

**Issue by forki** [haf/expecto#61]
![image](https://cloud.githubusercontent.com/assets/57396/21716982/55e62a88-d40e-11e6-8eca-95cdcdfa7568.png)

// @haf I assume you rake build script doesn't set the product version into the expecto.dll

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/21717007/7fedc32c-d40e-11e6-96eb-61a6ebbfb792.png)

**Comment by haf** [comment]
The Rakefile sets a version, yes. I just hadn't included the generated file before now.

**Comment by forki** [comment]
cool thx!
