### ISSUE TITLE
Change distribution error message

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [haf/expecto#63]
I don't think distribution error should display those part of message which are not not showing actual error for the case (so for example don't display `Missing elements from actual:` + empty line if there are no missing elements).

CC: @haf and @MNie

**Comment by MNie** [comment]
@Krzysztof-Cieslak  I agree, also the same with continsAll? If there are not any elements it shouldn't display:
`missing/extra elements from/in 'actual'`
`{}`
?
