### ISSUE TITLE
Parametised test suites

### ISSUE THREAD

**Issue by haf** [haf/expecto#69]
- Support globally parametising, e.g. a `TcpStreamFactory`
 - Support globally having a lock server, that given a category, returns an object that can be locked on, to ensure the critical region only is executed from one thread in the test suite
 - Support having a port generator, to fix issues like https://github.com/SuaveIO/suave/issues/341 but for testing, to avoid having to run [Suave's test suite in a sequenced manner](https://github.com/SuaveIO/suave/blob/master/Rakefile#L209)

This issue is to support passing data to every TestCode that supports input parameters. There's an implementation [for this](https://github.com/SuaveIO/suave/blob/master/src/Suave.Tests/Program.fs#L27) in [Suave that](https://github.com/SuaveIO/suave/blob/master/src/Suave.Tests/FuchuExtensions.fs) should be ported/imported into Expecto.

**Comment by Krzysztof-Cieslak** [comment]
Uhh....

This can be handled by `testFixture` or `testParam` (https://github.com/haf/expecto/blob/master/Expecto/Expecto.fs#L979-L986)

Or I don't understand something?

**Comment by haf** [comment]
Haha, nice catch. That's not documented though.

**Comment by haf** [comment]
@Krzysztof-Cieslak Ok, so I dived into this a little further (by documenting the above). What I was intending was what Suave does; allowing the test suite (or a range of tests) to be varied by param effectively. Similar to how Suave's tests are run:

<img width="555" alt="screen shot 2017-01-14 at 15 36 40" src="https://cloud.githubusercontent.com/assets/193115/21955619/42811b12-da6f-11e6-8821-9f6a112a064c.png">
