### ISSUE TITLE
Expecto logo

### ISSUE THREAD

**Issue by sergey-tihon** [haf/expecto#72]
Would love to hear opinions from fans
// @haf @forki @Krzysztof-Cieslak @MNie @AnthonyLloyd @cloudRoutine @adamchester 

![image](https://cloud.githubusercontent.com/assets/1197905/21821768/c965d092-d785-11e6-8564-5e8fa2bc38a5.png)
![image](https://cloud.githubusercontent.com/assets/1197905/21821640/647a24c6-d785-11e6-9f3c-1cb8ead57422.png)

**Comment by Krzysztof-Cieslak** [comment]
:+100:

**Comment by forki** [comment]
:kiss:

**Comment by adamchester** [comment]
❤️

**Comment by haf** [comment]
Hey @forki, surely this is not enterprise enough for you?

**Comment by forki** [comment]
@haf the issue with the moot summary is that it looks weird. Even on modern console output. Nobody in the room saw the smiley. It just was weird.

**Comment by haf** [comment]
;)

**Comment by forki** [comment]
But that's OK. We iterate on things. We should also iterate on jokes

**Comment by AnthonyLloyd** [comment]
👍 

I just see a series of boxes in powershell

**Comment by haf** [comment]
@forki I'm worse myself; I've been an enterprise dev for 10+ years now and there's no end in sight. Enterprise is good money so I don't mind. Btw, we should definitely have a beer sometime, when are you coming to Stockholm next? :)

@sergey-tihon Concretely, I think the logo is too warm in its colours, with both brown and orange being reds. Also, do we want more Harry?

In any case, we don't have a logo just yet, so let's make this the one? Albacore picks out the path from the fsproj file on publish, so just add an `Icon` element with the url to the properties and it'll be used.

**Comment by Krzysztof-Cieslak** [comment]
Could I join? ;]

**Comment by haf** [comment]
Yes why don't you all in this thread come to Stockholm for a few days and let me show you around? And for great conversation.

**Comment by AnthonyLloyd** [comment]
I'll be in Stockholm in the summer en famille for our hols.

**Comment by sergey-tihon** [comment]
@haf what about scarf and cold colors?
![image](https://cloud.githubusercontent.com/assets/1197905/21844119/7fae5c48-d7fe-11e6-9265-960b64ad42e6.png)

**Comment by haf** [comment]
@sergey-tihon When in doubt, use pastels. I do like the scarf =)

@AnthonyLloyd What dates?

**Comment by AnthonyLloyd** [comment]
Stockholm Mon 31st Jul-Wed 2nd Aug, Visby before, Malexander & Tyfta after.

**Comment by sergey-tihon** [comment]
@haf Updated colors
![image](https://cloud.githubusercontent.com/assets/1197905/21848069/1f2ff27a-d810-11e6-8136-3bc22b6cfbdd.png)

**Comment by haf** [comment]
Something more pastel, like 
![1f2ff27a-d810-11e6-8136-3bc22b6cfbdd copy](https://cloud.githubusercontent.com/assets/193115/21885791/8b5aa086-d8b9-11e6-8d00-1beb3dd583de.png)
 perhaps?
