### ISSUE TITLE
Tests hanging if config.``parallel`` = false

### ISSUE THREAD

**Issue by alfonsogarciacaro** [haf/expecto#83]
After updating Expecto from 1.1.2 to 3.1.0, when running the tests, the program just hangs and no breakpoint into any test gets hit. Apparently the problem is we're disabling the `parallel` flag in the configuration (note this worked in the old version):

```fsharp
runTests { defaultConfig with ``parallel`` = false } all
```

The problem goes away when just using the default config and using `testSequenced` for the tests we want to run in sequence. Note: something like the following doesn't work to run all tests in sequence:

```fsharp
all |> testSequenced |> runTests defaultConfig
```

**Comment by haf** [comment]
> The problem goes away when just using the default config and using testSequenced for the tests we want to run in parallel.

You mean, to run in sequence?

**Comment by alfonsogarciacaro** [comment]
Yes, sorry. I edited it and also fixed the version number. I'm closing this as it seems to be the same problem as #84, so the issue can be tracked. Please feel free to reopen if you'd rather keep this one.
