### ISSUE TITLE
Update to Expecto 3.0.2 broke our build

### ISSUE THREAD

**Issue by forki** [haf/expecto#84]
Something rather important broke between 3.0.1 and 3.0.2 and that breaks our build.
Is there anything known to be breaking? BTW: 3.1 is broken for us as well.

I diffed and didn't see anything obvious - apart from that huge change in the lock file.

/cc @theimowski @haf @Krzysztof-Cieslak

**Comment by forki** [comment]
we also have parallel = false.

Maybe releated to https://github.com/haf/expecto/issues/83 @alfonsogarciacaro 
But 3.0 and 3.01 is definetly working for us

**Comment by haf** [comment]
Hmm, my guess is that it's from these changes;

https://github.com/haf/expecto/commit/ef1d69f8bd8318e899b8cf3eb9df7aacb436257a#diff-312b950ecb6e71200586b2408ab6e821R813

If you'd do a minimal repro, I'm sure we could work through it.

/cc @AnthonyLloyd  (the commit referenced)

**Comment by forki** [comment]
not even sure where to start ;-(

**Comment by AnthonyLloyd** [comment]
Yes I think it is this. Its not taking account of parallel anymore.
Workaround is --parallel-workers 1.
Will submit fix today.

**Comment by forki** [comment]
thank you.

**Comment by alfonsogarciacaro** [comment]
I just run `paket update` yesterday. Probably it was v3.1.0 and I just made a mistake, I'll edit it. Thanks for getting into it!

**Comment by haf** [comment]
This also explains why Qvitoo's test-suite is hanging, actually ;).

**Comment by forki** [comment]
Lol. So we now have couple of canaries

**Comment by AnthonyLloyd** [comment]
@haf This is ready. I put in two tests also. I couldn't reproduce the hanging though.

Can I ask for interest why you run with parallel = false?

**Comment by haf** [comment]
@AnthonyLloyd Because I spawn both an EventStore in memory and a Suave server to test end-to-end in every unit test and tests' ports conflict. I haven't yet refactored a test to claim a port.

**Comment by forki** [comment]
We use it for Canopy.Mobile integration tests. That thing is clicking in an Android emulator...

**Comment by AnthonyLloyd** [comment]
Cool. These could be marked as testSequenced but if its all of them parallel = false is just the same.

I'm interested because of Stress testing #79.

First off I thought the stress testing would only be done on the parallel tests ignoring the sequenced. Sequenced ones could be just run once for stats.

Now I think if parallel = false or all sequenced they should be run repeatedly.
