### ISSUE TITLE
Run Sequenced test lists in parallel

### ISSUE THREAD

**Issue by isaacabraham** [haf/expecto#87]
I have two test lists, both of which are sequenced, because the tests within them affect data that is recreated before / torn down after each test.

However, each of the two test lists work on *different* data sets and could happily run in parallel. However at the moment when I place both test lists into a top-level test list, they are run one after the other.

Is there a way to run two sequenced test lists in parallel (but still run the tests within the lists in sequence, if you get my meaning)?

**Comment by AnthonyLloyd** [comment]
Sorry no that's not possible at the moment. Interesting feature though.

@haf what do you think?

**Comment by haf** [comment]
I've been thinking that you should be able to pass a lock name to the `testSequenced` function, letting it have a `Map<string, obj>` in the background, which it uses to lock.

That way you could just name your sequenced sets of tests by their data set name.

**Comment by AnthonyLloyd** [comment]
@isaacabraham as a workaround you can make your tests async and use the following locking (see https://fpish.net/topic/None/57147):

let lock = new SemaphoreSlim(1,1)

Around each async test:
lock.WaitAsync()
.....
lock.Release()

@haf I guess we have two types of testSequenced one with a lock name where the children need to be run sequentially and one that needs to be globally sequential like the perf tests. Should these have different names?

I think ultimately internally this shouldn't be done with real locking.  A better way I think would be to group tests by sequenced groups then treating these as a whole for parallel. Long sequences should be started early etc.

**Comment by isaacabraham** [comment]
@AnthonyLloyd Nice - I'll try that - I could probably write a reusable function that lifts a function into async and does this. I did actually try something similar using basic ``lock()`` but it didn't seem to work.

**Comment by haf** [comment]
Yes, if we can make the unit tests values (omg, we already have! ;)) then we should be able to run a [binpacking algo](http://www.fssnip.net/hG) on them to schedule their order and parallelism – that way long sequences start early.

I agree that we probably need a lock server that's async rather than an actual lock.

**Comment by AnthonyLloyd** [comment]
Happy to pick this up after I've finished stress testing in the next couple of days.

**Comment by isaacabraham** [comment]
Is there anything you need to do to "use" parallel sequences or should it just now happen automagically?

**Comment by AnthonyLloyd** [comment]
testSequencedGroup is what you need. Should all be good, let me know if not.
