### ISSUE TITLE
Allow specifying the Assembly to run tests in

### ISSUE THREAD

**Issue by mtnrbq** [haf/expecto#94]
I've added a new function to my fork of Expecto - runTestsInDifferentAssembly 
My particular use case is where I have the tests in a F# class library, but I need to run the tests from within a c# exe.

It's meeting my need, happy to contribute a PR if you believe it'd be of general use.

```FSharp
  /// Runs tests in a passed in assembly with the supplied command-line options.
  /// Returns 0 if all tests passed, otherwise 1
  let runTestsInDifferentAssembly config args (assembly:Assembly) =
    let config = { config with locate = getLocation (assembly) }
    testFromDifferentAssembly assembly
    |> Option.orDefault (TestList ([], Normal))
    |> runTestsWithArgs config args
```

**Comment by haf** [comment]
I think this for next version:

Extract an `Assembly` param from https://github.com/haf/expecto/blob/master/Expecto/Expecto.fs#L1541-L1542

Rename https://github.com/haf/expecto/blob/master/Expecto/Expecto.fs#L1540 to `runTestsInAssembly`

Then there's your function. Then below:

```fsharp
let runTestsInThisAssembly config args =
  runTestsInAssembly config args (Assembly.GetEntryAssembly())
```

Now we have both features and only one line more of code.

**Comment by haf** [comment]
Hi there. I'll be closing this issue tomorrow due to the lack of a PR/response.

**Comment by MecuSorin** [comment]
Hey Henrik, I think we can shoot 2 bunnies with a single bullet: use this to exercise the tests from Expecto.Focused.Tests (we can make Expecto.Tests to reference Expecto.Focused.Tests, make the focused test from Expecto.Focused.Tests to fail, and the normal test to succeed) run the tests from Expecto.Focused.Tests and check that fails. No need then to change the build.fsx and rakefile.
As a contra argument: this scenario is giving too much complexity for my taste.  What do you think?

Can I make a PR on this particular issue? 
I don't have an idea of proper testing the code now.

**Comment by haf** [comment]
I think it would make sense to test this by referencing your project. Go ahead and PR it. The return value of the main test suite should just be the sum of the two calls to test tests.

**Comment by mtnrbq** [comment]
Hi, I've made the PR for the change in Expecto.fs - I have been hung up on how best to add testing code. This is my first PR, any advice or guidance for future appreciated

**Comment by haf** [comment]
@mtnrbq See comment https://github.com/haf/expecto/issues/94#issuecomment-279134364

**Comment by mtnrbq** [comment]
@haf - started down the suggested path, hit a couple of issues: (Sorry if I've misunderstood some of the background, and overthought the approach)
1. Function is already named **runTestsInAssembly**, extracting assembly param will impact existing callers  
1. Function includes a call to **testFromThisAssembly()**, which calls **Assembly.GetEntryAssembly()**
1. Function runTestsInThisAssembly, existing callers will need to be updated to use this

Approach to resolve (assuming impact on existing callers acceptable)
* extract Assemby param as suggested
* call **testFromAssembly asm** as opposed to **testFromThisAssembly ()**
  * i.e. to take an assembly parameter.

New PR is based on this approach

**Comment by lfr** [comment]
This ticket is closed but it's unclear to me whether the PR has been merged?

**Comment by haf** [comment]
@lfr He closed his PR the same day as he sent it. I'm not at all sure what he wanted and this was a while ago now. The PR was not merged.

**Comment by mtnrbq** [comment]
Hi,

From memory it was unclear to me on the correct way to proceed, and I found another approach.

Regards
Rob

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
